package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TActivoFijo generated by hbm2java
 */
public class TActivoFijo  implements java.io.Serializable {


     private int idActivoFijo;
     private TEmpleado TEmpleado;
     private TProveedor TProveedor;
     private TTipoActivo TTipoActivo;
     private String codigoActivoFijo;
     private String marcaActivoFijo;
     private String modeloActivoFijo;
     private String serieActivoFijo;
     private String descripcionActivoFijo;
     private Date compraActivoFijo;
     private Date registroActivoFijo;
     private String numeroFacturaActivoFijo;
     private String estadoActivoFijo;
     private Set TBajaActivoFijos = new HashSet(0);
     private Set TDepreciacions = new HashSet(0);
     private Set TValorActivos = new HashSet(0);

    public TActivoFijo() {
    }

	
    public TActivoFijo(int idActivoFijo) {
        this.idActivoFijo = idActivoFijo;
    }
    public TActivoFijo(int idActivoFijo, TEmpleado TEmpleado, TProveedor TProveedor, TTipoActivo TTipoActivo, String codigoActivoFijo, String marcaActivoFijo, String modeloActivoFijo, String serieActivoFijo, String descripcionActivoFijo, Date compraActivoFijo, Date registroActivoFijo, String numeroFacturaActivoFijo, String estadoActivoFijo, Set TBajaActivoFijos, Set TDepreciacions, Set TValorActivos) {
       this.idActivoFijo = idActivoFijo;
       this.TEmpleado = TEmpleado;
       this.TProveedor = TProveedor;
       this.TTipoActivo = TTipoActivo;
       this.codigoActivoFijo = codigoActivoFijo;
       this.marcaActivoFijo = marcaActivoFijo;
       this.modeloActivoFijo = modeloActivoFijo;
       this.serieActivoFijo = serieActivoFijo;
       this.descripcionActivoFijo = descripcionActivoFijo;
       this.compraActivoFijo = compraActivoFijo;
       this.registroActivoFijo = registroActivoFijo;
       this.numeroFacturaActivoFijo = numeroFacturaActivoFijo;
       this.estadoActivoFijo = estadoActivoFijo;
       this.TBajaActivoFijos = TBajaActivoFijos;
       this.TDepreciacions = TDepreciacions;
       this.TValorActivos = TValorActivos;
    }
   
    public int getIdActivoFijo() {
        return this.idActivoFijo;
    }
    
    public void setIdActivoFijo(int idActivoFijo) {
        this.idActivoFijo = idActivoFijo;
    }
    public TEmpleado getTEmpleado() {
        return this.TEmpleado;
    }
    
    public void setTEmpleado(TEmpleado TEmpleado) {
        this.TEmpleado = TEmpleado;
    }
    public TProveedor getTProveedor() {
        return this.TProveedor;
    }
    
    public void setTProveedor(TProveedor TProveedor) {
        this.TProveedor = TProveedor;
    }
    public TTipoActivo getTTipoActivo() {
        return this.TTipoActivo;
    }
    
    public void setTTipoActivo(TTipoActivo TTipoActivo) {
        this.TTipoActivo = TTipoActivo;
    }
    public String getCodigoActivoFijo() {
        return this.codigoActivoFijo;
    }
    
    public void setCodigoActivoFijo(String codigoActivoFijo) {
        this.codigoActivoFijo = codigoActivoFijo;
    }
    public String getMarcaActivoFijo() {
        return this.marcaActivoFijo;
    }
    
    public void setMarcaActivoFijo(String marcaActivoFijo) {
        this.marcaActivoFijo = marcaActivoFijo;
    }
    public String getModeloActivoFijo() {
        return this.modeloActivoFijo;
    }
    
    public void setModeloActivoFijo(String modeloActivoFijo) {
        this.modeloActivoFijo = modeloActivoFijo;
    }
    public String getSerieActivoFijo() {
        return this.serieActivoFijo;
    }
    
    public void setSerieActivoFijo(String serieActivoFijo) {
        this.serieActivoFijo = serieActivoFijo;
    }
    public String getDescripcionActivoFijo() {
        return this.descripcionActivoFijo;
    }
    
    public void setDescripcionActivoFijo(String descripcionActivoFijo) {
        this.descripcionActivoFijo = descripcionActivoFijo;
    }
    public Date getCompraActivoFijo() {
        return this.compraActivoFijo;
    }
    
    public void setCompraActivoFijo(Date compraActivoFijo) {
        this.compraActivoFijo = compraActivoFijo;
    }
    public Date getRegistroActivoFijo() {
        return this.registroActivoFijo;
    }
    
    public void setRegistroActivoFijo(Date registroActivoFijo) {
        this.registroActivoFijo = registroActivoFijo;
    }
    public String getNumeroFacturaActivoFijo() {
        return this.numeroFacturaActivoFijo;
    }
    
    public void setNumeroFacturaActivoFijo(String numeroFacturaActivoFijo) {
        this.numeroFacturaActivoFijo = numeroFacturaActivoFijo;
    }
    public String getEstadoActivoFijo() {
        return this.estadoActivoFijo;
    }
    
    public void setEstadoActivoFijo(String estadoActivoFijo) {
        this.estadoActivoFijo = estadoActivoFijo;
    }
    public Set getTBajaActivoFijos() {
        return this.TBajaActivoFijos;
    }
    
    public void setTBajaActivoFijos(Set TBajaActivoFijos) {
        this.TBajaActivoFijos = TBajaActivoFijos;
    }
    public Set getTDepreciacions() {
        return this.TDepreciacions;
    }
    
    public void setTDepreciacions(Set TDepreciacions) {
        this.TDepreciacions = TDepreciacions;
    }
    public Set getTValorActivos() {
        return this.TValorActivos;
    }
    
    public void setTValorActivos(Set TValorActivos) {
        this.TValorActivos = TValorActivos;
    }




}


