package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TActivo generated by hbm2java
 */
public class TActivo  implements java.io.Serializable {


     private int idactivo;
     private TProyecto TProyecto;
     private String nombre;
     private String descripcion;
     private Integer estado;
     private BigDecimal valor;

    public TActivo() {
    }

	
    public TActivo(int idactivo) {
        this.idactivo = idactivo;
    }
    public TActivo(int idactivo, TProyecto TProyecto, String nombre, String descripcion, Integer estado, BigDecimal valor) {
       this.idactivo = idactivo;
       this.TProyecto = TProyecto;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estado = estado;
       this.valor = valor;
    }
   
    public int getIdactivo() {
        return this.idactivo;
    }
    
    public void setIdactivo(int idactivo) {
        this.idactivo = idactivo;
    }
    public TProyecto getTProyecto() {
        return this.TProyecto;
    }
    
    public void setTProyecto(TProyecto TProyecto) {
        this.TProyecto = TProyecto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }




}


