package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1



/**
 * TAgropecuario generated by hbm2java
 */
public class TAgropecuario  implements java.io.Serializable {


     private int idAgropecuario;
     private TProyecto TProyecto;
     private String actividadAgropecuario;
     private Integer tiempoAgropecuario;

    public TAgropecuario() {
    }

	
    public TAgropecuario(int idAgropecuario) {
        this.idAgropecuario = idAgropecuario;
    }
    public TAgropecuario(int idAgropecuario, TProyecto TProyecto, String actividadAgropecuario, Integer tiempoAgropecuario) {
       this.idAgropecuario = idAgropecuario;
       this.TProyecto = TProyecto;
       this.actividadAgropecuario = actividadAgropecuario;
       this.tiempoAgropecuario = tiempoAgropecuario;
    }
   
    public int getIdAgropecuario() {
        return this.idAgropecuario;
    }
    
    public void setIdAgropecuario(int idAgropecuario) {
        this.idAgropecuario = idAgropecuario;
    }
    public TProyecto getTProyecto() {
        return this.TProyecto;
    }
    
    public void setTProyecto(TProyecto TProyecto) {
        this.TProyecto = TProyecto;
    }
    public String getActividadAgropecuario() {
        return this.actividadAgropecuario;
    }
    
    public void setActividadAgropecuario(String actividadAgropecuario) {
        this.actividadAgropecuario = actividadAgropecuario;
    }
    public Integer getTiempoAgropecuario() {
        return this.tiempoAgropecuario;
    }
    
    public void setTiempoAgropecuario(Integer tiempoAgropecuario) {
        this.tiempoAgropecuario = tiempoAgropecuario;
    }




}


