package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TArea generated by hbm2java
 */
public class TArea  implements java.io.Serializable {


     private int idArea;
     private TEntidad TEntidad;
     private String nombreArea;
     private String codigoArea;
     private Boolean estadoArea;
     private Set TEmpleadoAreas = new HashSet(0);

    public TArea() {
    }

	
    public TArea(int idArea) {
        this.idArea = idArea;
    }
    public TArea(int idArea, TEntidad TEntidad, String nombreArea, String codigoArea, Boolean estadoArea, Set TEmpleadoAreas) {
       this.idArea = idArea;
       this.TEntidad = TEntidad;
       this.nombreArea = nombreArea;
       this.codigoArea = codigoArea;
       this.estadoArea = estadoArea;
       this.TEmpleadoAreas = TEmpleadoAreas;
    }
   
    public int getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(int idArea) {
        this.idArea = idArea;
    }
    public TEntidad getTEntidad() {
        return this.TEntidad;
    }
    
    public void setTEntidad(TEntidad TEntidad) {
        this.TEntidad = TEntidad;
    }
    public String getNombreArea() {
        return this.nombreArea;
    }
    
    public void setNombreArea(String nombreArea) {
        this.nombreArea = nombreArea;
    }
    public String getCodigoArea() {
        return this.codigoArea;
    }
    
    public void setCodigoArea(String codigoArea) {
        this.codigoArea = codigoArea;
    }
    public Boolean getEstadoArea() {
        return this.estadoArea;
    }
    
    public void setEstadoArea(Boolean estadoArea) {
        this.estadoArea = estadoArea;
    }
    public Set getTEmpleadoAreas() {
        return this.TEmpleadoAreas;
    }
    
    public void setTEmpleadoAreas(Set TEmpleadoAreas) {
        this.TEmpleadoAreas = TEmpleadoAreas;
    }




}


