package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TBajaActivoFijo generated by hbm2java
 */
public class TBajaActivoFijo  implements java.io.Serializable {


     private int idBajaActivoFijo;
     private TActivoFijo TActivoFijo;
     private TPartida TPartida;
     private String tipoBajaActivoFijo;
     private BigDecimal valorBajaActivoFijo;

    public TBajaActivoFijo() {
    }

	
    public TBajaActivoFijo(int idBajaActivoFijo) {
        this.idBajaActivoFijo = idBajaActivoFijo;
    }
    public TBajaActivoFijo(int idBajaActivoFijo, TActivoFijo TActivoFijo, TPartida TPartida, String tipoBajaActivoFijo, BigDecimal valorBajaActivoFijo) {
       this.idBajaActivoFijo = idBajaActivoFijo;
       this.TActivoFijo = TActivoFijo;
       this.TPartida = TPartida;
       this.tipoBajaActivoFijo = tipoBajaActivoFijo;
       this.valorBajaActivoFijo = valorBajaActivoFijo;
    }
   
    public int getIdBajaActivoFijo() {
        return this.idBajaActivoFijo;
    }
    
    public void setIdBajaActivoFijo(int idBajaActivoFijo) {
        this.idBajaActivoFijo = idBajaActivoFijo;
    }
    public TActivoFijo getTActivoFijo() {
        return this.TActivoFijo;
    }
    
    public void setTActivoFijo(TActivoFijo TActivoFijo) {
        this.TActivoFijo = TActivoFijo;
    }
    public TPartida getTPartida() {
        return this.TPartida;
    }
    
    public void setTPartida(TPartida TPartida) {
        this.TPartida = TPartida;
    }
    public String getTipoBajaActivoFijo() {
        return this.tipoBajaActivoFijo;
    }
    
    public void setTipoBajaActivoFijo(String tipoBajaActivoFijo) {
        this.tipoBajaActivoFijo = tipoBajaActivoFijo;
    }
    public BigDecimal getValorBajaActivoFijo() {
        return this.valorBajaActivoFijo;
    }
    
    public void setValorBajaActivoFijo(BigDecimal valorBajaActivoFijo) {
        this.valorBajaActivoFijo = valorBajaActivoFijo;
    }




}


