package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TCargo generated by hbm2java
 */
public class TCargo  implements java.io.Serializable {


     private int idCargo;
     private String nombreCargo;
     private Integer estadoCargo;
     private Integer tipoCargo;
     private Set TEmpleadoCargos = new HashSet(0);

    public TCargo() {
    }

	
    public TCargo(int idCargo) {
        this.idCargo = idCargo;
    }
    public TCargo(int idCargo, String nombreCargo, Integer estadoCargo, Integer tipoCargo, Set TEmpleadoCargos) {
       this.idCargo = idCargo;
       this.nombreCargo = nombreCargo;
       this.estadoCargo = estadoCargo;
       this.tipoCargo = tipoCargo;
       this.TEmpleadoCargos = TEmpleadoCargos;
    }
   
    public int getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(int idCargo) {
        this.idCargo = idCargo;
    }
    public String getNombreCargo() {
        return this.nombreCargo;
    }
    
    public void setNombreCargo(String nombreCargo) {
        this.nombreCargo = nombreCargo;
    }
    public Integer getEstadoCargo() {
        return this.estadoCargo;
    }
    
    public void setEstadoCargo(Integer estadoCargo) {
        this.estadoCargo = estadoCargo;
    }
    public Integer getTipoCargo() {
        return this.tipoCargo;
    }
    
    public void setTipoCargo(Integer tipoCargo) {
        this.tipoCargo = tipoCargo;
    }
    public Set getTEmpleadoCargos() {
        return this.TEmpleadoCargos;
    }
    
    public void setTEmpleadoCargos(Set TEmpleadoCargos) {
        this.TEmpleadoCargos = TEmpleadoCargos;
    }




}


