package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1



/**
 * TComentario generated by hbm2java
 */
public class TComentario  implements java.io.Serializable {


     private int idcomentario;
     private TEmpleado TEmpleado;
     private TProyecto TProyecto;
     private String descripcion;
     private Integer estado;

    public TComentario() {
    }

	
    public TComentario(int idcomentario) {
        this.idcomentario = idcomentario;
    }
    public TComentario(int idcomentario, TEmpleado TEmpleado, TProyecto TProyecto, String descripcion, Integer estado) {
       this.idcomentario = idcomentario;
       this.TEmpleado = TEmpleado;
       this.TProyecto = TProyecto;
       this.descripcion = descripcion;
       this.estado = estado;
    }
   
    public int getIdcomentario() {
        return this.idcomentario;
    }
    
    public void setIdcomentario(int idcomentario) {
        this.idcomentario = idcomentario;
    }
    public TEmpleado getTEmpleado() {
        return this.TEmpleado;
    }
    
    public void setTEmpleado(TEmpleado TEmpleado) {
        this.TEmpleado = TEmpleado;
    }
    public TProyecto getTProyecto() {
        return this.TProyecto;
    }
    
    public void setTProyecto(TProyecto TProyecto) {
        this.TProyecto = TProyecto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }




}


