package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TConfiguracionAgronegocio generated by hbm2java
 */
public class TConfiguracionAgronegocio  implements java.io.Serializable {


     private int idConfiguracionAgronegocio;
     private BigDecimal tasaComisionAgronegocio;
     private BigDecimal tasaInteresAgronegocio;
     private BigDecimal tasaMoraAgronegocio;
     private Date vigenciaAgronegocio;
     private Boolean estadoConfiguracion;
     private Set TAgronegocios = new HashSet(0);

    public TConfiguracionAgronegocio() {
    }

	
    public TConfiguracionAgronegocio(int idConfiguracionAgronegocio) {
        this.idConfiguracionAgronegocio = idConfiguracionAgronegocio;
    }
    public TConfiguracionAgronegocio(int idConfiguracionAgronegocio, BigDecimal tasaComisionAgronegocio, BigDecimal tasaInteresAgronegocio, BigDecimal tasaMoraAgronegocio, Date vigenciaAgronegocio, Boolean estadoConfiguracion, Set TAgronegocios) {
       this.idConfiguracionAgronegocio = idConfiguracionAgronegocio;
       this.tasaComisionAgronegocio = tasaComisionAgronegocio;
       this.tasaInteresAgronegocio = tasaInteresAgronegocio;
       this.tasaMoraAgronegocio = tasaMoraAgronegocio;
       this.vigenciaAgronegocio = vigenciaAgronegocio;
       this.estadoConfiguracion = estadoConfiguracion;
       this.TAgronegocios = TAgronegocios;
    }
   
    public int getIdConfiguracionAgronegocio() {
        return this.idConfiguracionAgronegocio;
    }
    
    public void setIdConfiguracionAgronegocio(int idConfiguracionAgronegocio) {
        this.idConfiguracionAgronegocio = idConfiguracionAgronegocio;
    }
    public BigDecimal getTasaComisionAgronegocio() {
        return this.tasaComisionAgronegocio;
    }
    
    public void setTasaComisionAgronegocio(BigDecimal tasaComisionAgronegocio) {
        this.tasaComisionAgronegocio = tasaComisionAgronegocio;
    }
    public BigDecimal getTasaInteresAgronegocio() {
        return this.tasaInteresAgronegocio;
    }
    
    public void setTasaInteresAgronegocio(BigDecimal tasaInteresAgronegocio) {
        this.tasaInteresAgronegocio = tasaInteresAgronegocio;
    }
    public BigDecimal getTasaMoraAgronegocio() {
        return this.tasaMoraAgronegocio;
    }
    
    public void setTasaMoraAgronegocio(BigDecimal tasaMoraAgronegocio) {
        this.tasaMoraAgronegocio = tasaMoraAgronegocio;
    }
    public Date getVigenciaAgronegocio() {
        return this.vigenciaAgronegocio;
    }
    
    public void setVigenciaAgronegocio(Date vigenciaAgronegocio) {
        this.vigenciaAgronegocio = vigenciaAgronegocio;
    }
    public Boolean getEstadoConfiguracion() {
        return this.estadoConfiguracion;
    }
    
    public void setEstadoConfiguracion(Boolean estadoConfiguracion) {
        this.estadoConfiguracion = estadoConfiguracion;
    }
    public Set getTAgronegocios() {
        return this.TAgronegocios;
    }
    
    public void setTAgronegocios(Set TAgronegocios) {
        this.TAgronegocios = TAgronegocios;
    }




}


