package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1



/**
 * TConfiguracion generated by hbm2java
 */
public class TConfiguracion  implements java.io.Serializable {


     private int idConfiguracion;
     private TEntidad TEntidad;
     private String tipoConfiguracion;
     private String activoConfiguracion;
     private String areaConfiguracion;
     private String cuentaConfiguracion;

    public TConfiguracion() {
    }

	
    public TConfiguracion(int idConfiguracion) {
        this.idConfiguracion = idConfiguracion;
    }
    public TConfiguracion(int idConfiguracion, TEntidad TEntidad, String tipoConfiguracion, String activoConfiguracion, String areaConfiguracion, String cuentaConfiguracion) {
       this.idConfiguracion = idConfiguracion;
       this.TEntidad = TEntidad;
       this.tipoConfiguracion = tipoConfiguracion;
       this.activoConfiguracion = activoConfiguracion;
       this.areaConfiguracion = areaConfiguracion;
       this.cuentaConfiguracion = cuentaConfiguracion;
    }
   
    public int getIdConfiguracion() {
        return this.idConfiguracion;
    }
    
    public void setIdConfiguracion(int idConfiguracion) {
        this.idConfiguracion = idConfiguracion;
    }
    public TEntidad getTEntidad() {
        return this.TEntidad;
    }
    
    public void setTEntidad(TEntidad TEntidad) {
        this.TEntidad = TEntidad;
    }
    public String getTipoConfiguracion() {
        return this.tipoConfiguracion;
    }
    
    public void setTipoConfiguracion(String tipoConfiguracion) {
        this.tipoConfiguracion = tipoConfiguracion;
    }
    public String getActivoConfiguracion() {
        return this.activoConfiguracion;
    }
    
    public void setActivoConfiguracion(String activoConfiguracion) {
        this.activoConfiguracion = activoConfiguracion;
    }
    public String getAreaConfiguracion() {
        return this.areaConfiguracion;
    }
    
    public void setAreaConfiguracion(String areaConfiguracion) {
        this.areaConfiguracion = areaConfiguracion;
    }
    public String getCuentaConfiguracion() {
        return this.cuentaConfiguracion;
    }
    
    public void setCuentaConfiguracion(String cuentaConfiguracion) {
        this.cuentaConfiguracion = cuentaConfiguracion;
    }




}


