package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TCooperativa generated by hbm2java
 */
public class TCooperativa  implements java.io.Serializable {


     private int idCooperativa;
     private TProyecto TProyecto;
     private BigDecimal areaProducida;
     private BigDecimal creditoAnterior;
     private String presupuesto;
     private String balanceGeneral;
     private String acuerdoSolicitud;
     private BigDecimal activoCorriente;
     private BigDecimal activoNocorriente;
     private BigDecimal pasivoCorriente;
     private BigDecimal pasivoNocorriente;
     private BigDecimal patrimonio;

    public TCooperativa() {
    }

	
    public TCooperativa(int idCooperativa) {
        this.idCooperativa = idCooperativa;
    }
    public TCooperativa(int idCooperativa, TProyecto TProyecto, BigDecimal areaProducida, BigDecimal creditoAnterior, String presupuesto, String balanceGeneral, String acuerdoSolicitud, BigDecimal activoCorriente, BigDecimal activoNocorriente, BigDecimal pasivoCorriente, BigDecimal pasivoNocorriente, BigDecimal patrimonio) {
       this.idCooperativa = idCooperativa;
       this.TProyecto = TProyecto;
       this.areaProducida = areaProducida;
       this.creditoAnterior = creditoAnterior;
       this.presupuesto = presupuesto;
       this.balanceGeneral = balanceGeneral;
       this.acuerdoSolicitud = acuerdoSolicitud;
       this.activoCorriente = activoCorriente;
       this.activoNocorriente = activoNocorriente;
       this.pasivoCorriente = pasivoCorriente;
       this.pasivoNocorriente = pasivoNocorriente;
       this.patrimonio = patrimonio;
    }
   
    public int getIdCooperativa() {
        return this.idCooperativa;
    }
    
    public void setIdCooperativa(int idCooperativa) {
        this.idCooperativa = idCooperativa;
    }
    public TProyecto getTProyecto() {
        return this.TProyecto;
    }
    
    public void setTProyecto(TProyecto TProyecto) {
        this.TProyecto = TProyecto;
    }
    public BigDecimal getAreaProducida() {
        return this.areaProducida;
    }
    
    public void setAreaProducida(BigDecimal areaProducida) {
        this.areaProducida = areaProducida;
    }
    public BigDecimal getCreditoAnterior() {
        return this.creditoAnterior;
    }
    
    public void setCreditoAnterior(BigDecimal creditoAnterior) {
        this.creditoAnterior = creditoAnterior;
    }
    public String getPresupuesto() {
        return this.presupuesto;
    }
    
    public void setPresupuesto(String presupuesto) {
        this.presupuesto = presupuesto;
    }
    public String getBalanceGeneral() {
        return this.balanceGeneral;
    }
    
    public void setBalanceGeneral(String balanceGeneral) {
        this.balanceGeneral = balanceGeneral;
    }
    public String getAcuerdoSolicitud() {
        return this.acuerdoSolicitud;
    }
    
    public void setAcuerdoSolicitud(String acuerdoSolicitud) {
        this.acuerdoSolicitud = acuerdoSolicitud;
    }
    public BigDecimal getActivoCorriente() {
        return this.activoCorriente;
    }
    
    public void setActivoCorriente(BigDecimal activoCorriente) {
        this.activoCorriente = activoCorriente;
    }
    public BigDecimal getActivoNocorriente() {
        return this.activoNocorriente;
    }
    
    public void setActivoNocorriente(BigDecimal activoNocorriente) {
        this.activoNocorriente = activoNocorriente;
    }
    public BigDecimal getPasivoCorriente() {
        return this.pasivoCorriente;
    }
    
    public void setPasivoCorriente(BigDecimal pasivoCorriente) {
        this.pasivoCorriente = pasivoCorriente;
    }
    public BigDecimal getPasivoNocorriente() {
        return this.pasivoNocorriente;
    }
    
    public void setPasivoNocorriente(BigDecimal pasivoNocorriente) {
        this.pasivoNocorriente = pasivoNocorriente;
    }
    public BigDecimal getPatrimonio() {
        return this.patrimonio;
    }
    
    public void setPatrimonio(BigDecimal patrimonio) {
        this.patrimonio = patrimonio;
    }




}


