package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TCuenta generated by hbm2java
 */
public class TCuenta  implements java.io.Serializable {


     private int idCuenta;
     private TCuenta TCuenta;
     private TEntidad TEntidad;
     private String codigoCuenta;
     private String nombreCuenta;
     private Date fechaCuenta;
     private String naturalezaCuenta;
     private Boolean estadoCuenta;
     private Set TTipoActivosForIdCuentaVentaTipo = new HashSet(0);
     private Set TTipoActivosForIdCuentaDepreciacionTipo = new HashSet(0);
     private Set TCuentas = new HashSet(0);
     private Set TTipoActivosForIdCuentaGastoTipo = new HashSet(0);
     private Set TEstructuras = new HashSet(0);
     private Set TTipoActivosForIdCuentaActivoTipo = new HashSet(0);
     private Set TDetallePartidas = new HashSet(0);

    public TCuenta() {
    }

	
    public TCuenta(int idCuenta) {
        this.idCuenta = idCuenta;
    }
    public TCuenta(int idCuenta, TCuenta TCuenta, TEntidad TEntidad, String codigoCuenta, String nombreCuenta, Date fechaCuenta, String naturalezaCuenta, Boolean estadoCuenta, Set TTipoActivosForIdCuentaVentaTipo, Set TTipoActivosForIdCuentaDepreciacionTipo, Set TCuentas, Set TTipoActivosForIdCuentaGastoTipo, Set TEstructuras, Set TTipoActivosForIdCuentaActivoTipo, Set TDetallePartidas) {
       this.idCuenta = idCuenta;
       this.TCuenta = TCuenta;
       this.TEntidad = TEntidad;
       this.codigoCuenta = codigoCuenta;
       this.nombreCuenta = nombreCuenta;
       this.fechaCuenta = fechaCuenta;
       this.naturalezaCuenta = naturalezaCuenta;
       this.estadoCuenta = estadoCuenta;
       this.TTipoActivosForIdCuentaVentaTipo = TTipoActivosForIdCuentaVentaTipo;
       this.TTipoActivosForIdCuentaDepreciacionTipo = TTipoActivosForIdCuentaDepreciacionTipo;
       this.TCuentas = TCuentas;
       this.TTipoActivosForIdCuentaGastoTipo = TTipoActivosForIdCuentaGastoTipo;
       this.TEstructuras = TEstructuras;
       this.TTipoActivosForIdCuentaActivoTipo = TTipoActivosForIdCuentaActivoTipo;
       this.TDetallePartidas = TDetallePartidas;
    }
   
    public int getIdCuenta() {
        return this.idCuenta;
    }
    
    public void setIdCuenta(int idCuenta) {
        this.idCuenta = idCuenta;
    }
    public TCuenta getTCuenta() {
        return this.TCuenta;
    }
    
    public void setTCuenta(TCuenta TCuenta) {
        this.TCuenta = TCuenta;
    }
    public TEntidad getTEntidad() {
        return this.TEntidad;
    }
    
    public void setTEntidad(TEntidad TEntidad) {
        this.TEntidad = TEntidad;
    }
    public String getCodigoCuenta() {
        return this.codigoCuenta;
    }
    
    public void setCodigoCuenta(String codigoCuenta) {
        this.codigoCuenta = codigoCuenta;
    }
    public String getNombreCuenta() {
        return this.nombreCuenta;
    }
    
    public void setNombreCuenta(String nombreCuenta) {
        this.nombreCuenta = nombreCuenta;
    }
    public Date getFechaCuenta() {
        return this.fechaCuenta;
    }
    
    public void setFechaCuenta(Date fechaCuenta) {
        this.fechaCuenta = fechaCuenta;
    }
    public String getNaturalezaCuenta() {
        return this.naturalezaCuenta;
    }
    
    public void setNaturalezaCuenta(String naturalezaCuenta) {
        this.naturalezaCuenta = naturalezaCuenta;
    }
    public Boolean getEstadoCuenta() {
        return this.estadoCuenta;
    }
    
    public void setEstadoCuenta(Boolean estadoCuenta) {
        this.estadoCuenta = estadoCuenta;
    }
    public Set getTTipoActivosForIdCuentaVentaTipo() {
        return this.TTipoActivosForIdCuentaVentaTipo;
    }
    
    public void setTTipoActivosForIdCuentaVentaTipo(Set TTipoActivosForIdCuentaVentaTipo) {
        this.TTipoActivosForIdCuentaVentaTipo = TTipoActivosForIdCuentaVentaTipo;
    }
    public Set getTTipoActivosForIdCuentaDepreciacionTipo() {
        return this.TTipoActivosForIdCuentaDepreciacionTipo;
    }
    
    public void setTTipoActivosForIdCuentaDepreciacionTipo(Set TTipoActivosForIdCuentaDepreciacionTipo) {
        this.TTipoActivosForIdCuentaDepreciacionTipo = TTipoActivosForIdCuentaDepreciacionTipo;
    }
    public Set getTCuentas() {
        return this.TCuentas;
    }
    
    public void setTCuentas(Set TCuentas) {
        this.TCuentas = TCuentas;
    }
    public Set getTTipoActivosForIdCuentaGastoTipo() {
        return this.TTipoActivosForIdCuentaGastoTipo;
    }
    
    public void setTTipoActivosForIdCuentaGastoTipo(Set TTipoActivosForIdCuentaGastoTipo) {
        this.TTipoActivosForIdCuentaGastoTipo = TTipoActivosForIdCuentaGastoTipo;
    }
    public Set getTEstructuras() {
        return this.TEstructuras;
    }
    
    public void setTEstructuras(Set TEstructuras) {
        this.TEstructuras = TEstructuras;
    }
    public Set getTTipoActivosForIdCuentaActivoTipo() {
        return this.TTipoActivosForIdCuentaActivoTipo;
    }
    
    public void setTTipoActivosForIdCuentaActivoTipo(Set TTipoActivosForIdCuentaActivoTipo) {
        this.TTipoActivosForIdCuentaActivoTipo = TTipoActivosForIdCuentaActivoTipo;
    }
    public Set getTDetallePartidas() {
        return this.TDetallePartidas;
    }
    
    public void setTDetallePartidas(Set TDetallePartidas) {
        this.TDetallePartidas = TDetallePartidas;
    }




}


