package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TDepartamento generated by hbm2java
 */
public class TDepartamento  implements java.io.Serializable {


     private int idDepartamento;
     private String nombreDepartamento;
     private Boolean estadoDepartamento;
     private Set TMunicipios = new HashSet(0);

    public TDepartamento() {
    }

	
    public TDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public TDepartamento(int idDepartamento, String nombreDepartamento, Boolean estadoDepartamento, Set TMunicipios) {
       this.idDepartamento = idDepartamento;
       this.nombreDepartamento = nombreDepartamento;
       this.estadoDepartamento = estadoDepartamento;
       this.TMunicipios = TMunicipios;
    }
   
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public Boolean getEstadoDepartamento() {
        return this.estadoDepartamento;
    }
    
    public void setEstadoDepartamento(Boolean estadoDepartamento) {
        this.estadoDepartamento = estadoDepartamento;
    }
    public Set getTMunicipios() {
        return this.TMunicipios;
    }
    
    public void setTMunicipios(Set TMunicipios) {
        this.TMunicipios = TMunicipios;
    }




}


