package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TDetallePartida generated by hbm2java
 */
public class TDetallePartida  implements java.io.Serializable {


     private int idDetallePartida;
     private TCuenta TCuenta;
     private TPartida TPartida;
     private BigDecimal saldoDetallePartida;
     private String tipoSaldoDetallePartida;

    public TDetallePartida() {
    }

	
    public TDetallePartida(int idDetallePartida) {
        this.idDetallePartida = idDetallePartida;
    }
    public TDetallePartida(int idDetallePartida, TCuenta TCuenta, TPartida TPartida, BigDecimal saldoDetallePartida, String tipoSaldoDetallePartida) {
       this.idDetallePartida = idDetallePartida;
       this.TCuenta = TCuenta;
       this.TPartida = TPartida;
       this.saldoDetallePartida = saldoDetallePartida;
       this.tipoSaldoDetallePartida = tipoSaldoDetallePartida;
    }
   
    public int getIdDetallePartida() {
        return this.idDetallePartida;
    }
    
    public void setIdDetallePartida(int idDetallePartida) {
        this.idDetallePartida = idDetallePartida;
    }
    public TCuenta getTCuenta() {
        return this.TCuenta;
    }
    
    public void setTCuenta(TCuenta TCuenta) {
        this.TCuenta = TCuenta;
    }
    public TPartida getTPartida() {
        return this.TPartida;
    }
    
    public void setTPartida(TPartida TPartida) {
        this.TPartida = TPartida;
    }
    public BigDecimal getSaldoDetallePartida() {
        return this.saldoDetallePartida;
    }
    
    public void setSaldoDetallePartida(BigDecimal saldoDetallePartida) {
        this.saldoDetallePartida = saldoDetallePartida;
    }
    public String getTipoSaldoDetallePartida() {
        return this.tipoSaldoDetallePartida;
    }
    
    public void setTipoSaldoDetallePartida(String tipoSaldoDetallePartida) {
        this.tipoSaldoDetallePartida = tipoSaldoDetallePartida;
    }




}


