package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TEgreso generated by hbm2java
 */
public class TEgreso  implements java.io.Serializable {


     private int idegreso;
     private TProyecto TProyecto;
     private String nombre;
     private String descripcion;
     private BigDecimal valor;
     private Integer estado;

    public TEgreso() {
    }

	
    public TEgreso(int idegreso) {
        this.idegreso = idegreso;
    }
    public TEgreso(int idegreso, TProyecto TProyecto, String nombre, String descripcion, BigDecimal valor, Integer estado) {
       this.idegreso = idegreso;
       this.TProyecto = TProyecto;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.valor = valor;
       this.estado = estado;
    }
   
    public int getIdegreso() {
        return this.idegreso;
    }
    
    public void setIdegreso(int idegreso) {
        this.idegreso = idegreso;
    }
    public TProyecto getTProyecto() {
        return this.TProyecto;
    }
    
    public void setTProyecto(TProyecto TProyecto) {
        this.TProyecto = TProyecto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }




}


