package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TEmpleadoCargo generated by hbm2java
 */
public class TEmpleadoCargo  implements java.io.Serializable {


     private int idEmpleadoCargo;
     private TCargo TCargo;
     private TEmpleado TEmpleado;
     private Date fechainicioEmpleadoCargo;
     private Date fechafinEmpleadoCargo;
     private Boolean estadoEmpleadoCargo;

    public TEmpleadoCargo() {
    }

	
    public TEmpleadoCargo(int idEmpleadoCargo) {
        this.idEmpleadoCargo = idEmpleadoCargo;
    }
    public TEmpleadoCargo(int idEmpleadoCargo, TCargo TCargo, TEmpleado TEmpleado, Date fechainicioEmpleadoCargo, Date fechafinEmpleadoCargo, Boolean estadoEmpleadoCargo) {
       this.idEmpleadoCargo = idEmpleadoCargo;
       this.TCargo = TCargo;
       this.TEmpleado = TEmpleado;
       this.fechainicioEmpleadoCargo = fechainicioEmpleadoCargo;
       this.fechafinEmpleadoCargo = fechafinEmpleadoCargo;
       this.estadoEmpleadoCargo = estadoEmpleadoCargo;
    }
   
    public int getIdEmpleadoCargo() {
        return this.idEmpleadoCargo;
    }
    
    public void setIdEmpleadoCargo(int idEmpleadoCargo) {
        this.idEmpleadoCargo = idEmpleadoCargo;
    }
    public TCargo getTCargo() {
        return this.TCargo;
    }
    
    public void setTCargo(TCargo TCargo) {
        this.TCargo = TCargo;
    }
    public TEmpleado getTEmpleado() {
        return this.TEmpleado;
    }
    
    public void setTEmpleado(TEmpleado TEmpleado) {
        this.TEmpleado = TEmpleado;
    }
    public Date getFechainicioEmpleadoCargo() {
        return this.fechainicioEmpleadoCargo;
    }
    
    public void setFechainicioEmpleadoCargo(Date fechainicioEmpleadoCargo) {
        this.fechainicioEmpleadoCargo = fechainicioEmpleadoCargo;
    }
    public Date getFechafinEmpleadoCargo() {
        return this.fechafinEmpleadoCargo;
    }
    
    public void setFechafinEmpleadoCargo(Date fechafinEmpleadoCargo) {
        this.fechafinEmpleadoCargo = fechafinEmpleadoCargo;
    }
    public Boolean getEstadoEmpleadoCargo() {
        return this.estadoEmpleadoCargo;
    }
    
    public void setEstadoEmpleadoCargo(Boolean estadoEmpleadoCargo) {
        this.estadoEmpleadoCargo = estadoEmpleadoCargo;
    }




}


