package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1



/**
 * TEmpleadoCredito generated by hbm2java
 */
public class TEmpleadoCredito  implements java.io.Serializable {


     private int idEmpleadoCredito;
     private TProyecto TProyecto;

    public TEmpleadoCredito() {
    }

	
    public TEmpleadoCredito(int idEmpleadoCredito) {
        this.idEmpleadoCredito = idEmpleadoCredito;
    }
    public TEmpleadoCredito(int idEmpleadoCredito, TProyecto TProyecto) {
       this.idEmpleadoCredito = idEmpleadoCredito;
       this.TProyecto = TProyecto;
    }
   
    public int getIdEmpleadoCredito() {
        return this.idEmpleadoCredito;
    }
    
    public void setIdEmpleadoCredito(int idEmpleadoCredito) {
        this.idEmpleadoCredito = idEmpleadoCredito;
    }
    public TProyecto getTProyecto() {
        return this.TProyecto;
    }
    
    public void setTProyecto(TProyecto TProyecto) {
        this.TProyecto = TProyecto;
    }




}


