package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1



/**
 * TEmpleadoArea generated by hbm2java
 */
public class TEmpleadoArea  implements java.io.Serializable {


     private int idEmpleadoArea;
     private TArea TArea;
     private TEmpleado TEmpleado;

    public TEmpleadoArea() {
    }

	
    public TEmpleadoArea(int idEmpleadoArea) {
        this.idEmpleadoArea = idEmpleadoArea;
    }
    public TEmpleadoArea(int idEmpleadoArea, TArea TArea, TEmpleado TEmpleado) {
       this.idEmpleadoArea = idEmpleadoArea;
       this.TArea = TArea;
       this.TEmpleado = TEmpleado;
    }
   
    public int getIdEmpleadoArea() {
        return this.idEmpleadoArea;
    }
    
    public void setIdEmpleadoArea(int idEmpleadoArea) {
        this.idEmpleadoArea = idEmpleadoArea;
    }
    public TArea getTArea() {
        return this.TArea;
    }
    
    public void setTArea(TArea TArea) {
        this.TArea = TArea;
    }
    public TEmpleado getTEmpleado() {
        return this.TEmpleado;
    }
    
    public void setTEmpleado(TEmpleado TEmpleado) {
        this.TEmpleado = TEmpleado;
    }




}


