package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TEmpleado generated by hbm2java
 */
public class TEmpleado  implements java.io.Serializable {


     private int idEmpleado;
     private String nombreEmpleado;
     private String correoEmpleado;
     private String duiEmpleado;
     private String nitEmpleado;
     private Date fechanacimientoEmpleado;
     private BigDecimal salarioEmpleado;
     private Date fechaingresoEmpleado;
     private String telefonoEmpleado;
     private String celularEmpleado;
     private String sexoEmpleado;
     private String apellidoEmpleado;
     private Boolean estadoEmpleado;
     private String fotoEmpleado;
     private String lugarNacimientoEmpleado;
     private Integer tipoEmpleado;
     private Boolean estadoSocio;
     private Set TCapacitacions = new HashSet(0);
     private Set TAsesorias = new HashSet(0);
     private Set TEmpleadoCargos = new HashSet(0);
     private Set TOcupacions = new HashSet(0);
     private Set TComentarios = new HashSet(0);
     private Set TSugerencias = new HashSet(0);
     private Set TActivoFijos = new HashSet(0);
     private Set TMunicipioEmpleados = new HashSet(0);
     private Set TUsuarios = new HashSet(0);
     private Set TEmpleadoAreas = new HashSet(0);

    public TEmpleado() {
    }

	
    public TEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public TEmpleado(int idEmpleado, String nombreEmpleado, String correoEmpleado, String duiEmpleado, String nitEmpleado, Date fechanacimientoEmpleado, BigDecimal salarioEmpleado, Date fechaingresoEmpleado, String telefonoEmpleado, String celularEmpleado, String sexoEmpleado, String apellidoEmpleado, Boolean estadoEmpleado, String fotoEmpleado, String lugarNacimientoEmpleado, Integer tipoEmpleado, Boolean estadoSocio, Set TCapacitacions, Set TAsesorias, Set TEmpleadoCargos, Set TOcupacions, Set TComentarios, Set TSugerencias, Set TActivoFijos, Set TMunicipioEmpleados, Set TUsuarios, Set TEmpleadoAreas) {
       this.idEmpleado = idEmpleado;
       this.nombreEmpleado = nombreEmpleado;
       this.correoEmpleado = correoEmpleado;
       this.duiEmpleado = duiEmpleado;
       this.nitEmpleado = nitEmpleado;
       this.fechanacimientoEmpleado = fechanacimientoEmpleado;
       this.salarioEmpleado = salarioEmpleado;
       this.fechaingresoEmpleado = fechaingresoEmpleado;
       this.telefonoEmpleado = telefonoEmpleado;
       this.celularEmpleado = celularEmpleado;
       this.sexoEmpleado = sexoEmpleado;
       this.apellidoEmpleado = apellidoEmpleado;
       this.estadoEmpleado = estadoEmpleado;
       this.fotoEmpleado = fotoEmpleado;
       this.lugarNacimientoEmpleado = lugarNacimientoEmpleado;
       this.tipoEmpleado = tipoEmpleado;
       this.estadoSocio = estadoSocio;
       this.TCapacitacions = TCapacitacions;
       this.TAsesorias = TAsesorias;
       this.TEmpleadoCargos = TEmpleadoCargos;
       this.TOcupacions = TOcupacions;
       this.TComentarios = TComentarios;
       this.TSugerencias = TSugerencias;
       this.TActivoFijos = TActivoFijos;
       this.TMunicipioEmpleados = TMunicipioEmpleados;
       this.TUsuarios = TUsuarios;
       this.TEmpleadoAreas = TEmpleadoAreas;
    }
   
    public int getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(int idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public String getNombreEmpleado() {
        return this.nombreEmpleado;
    }
    
    public void setNombreEmpleado(String nombreEmpleado) {
        this.nombreEmpleado = nombreEmpleado;
    }
    public String getCorreoEmpleado() {
        return this.correoEmpleado;
    }
    
    public void setCorreoEmpleado(String correoEmpleado) {
        this.correoEmpleado = correoEmpleado;
    }
    public String getDuiEmpleado() {
        return this.duiEmpleado;
    }
    
    public void setDuiEmpleado(String duiEmpleado) {
        this.duiEmpleado = duiEmpleado;
    }
    public String getNitEmpleado() {
        return this.nitEmpleado;
    }
    
    public void setNitEmpleado(String nitEmpleado) {
        this.nitEmpleado = nitEmpleado;
    }
    public Date getFechanacimientoEmpleado() {
        return this.fechanacimientoEmpleado;
    }
    
    public void setFechanacimientoEmpleado(Date fechanacimientoEmpleado) {
        this.fechanacimientoEmpleado = fechanacimientoEmpleado;
    }
    public BigDecimal getSalarioEmpleado() {
        return this.salarioEmpleado;
    }
    
    public void setSalarioEmpleado(BigDecimal salarioEmpleado) {
        this.salarioEmpleado = salarioEmpleado;
    }
    public Date getFechaingresoEmpleado() {
        return this.fechaingresoEmpleado;
    }
    
    public void setFechaingresoEmpleado(Date fechaingresoEmpleado) {
        this.fechaingresoEmpleado = fechaingresoEmpleado;
    }
    public String getTelefonoEmpleado() {
        return this.telefonoEmpleado;
    }
    
    public void setTelefonoEmpleado(String telefonoEmpleado) {
        this.telefonoEmpleado = telefonoEmpleado;
    }
    public String getCelularEmpleado() {
        return this.celularEmpleado;
    }
    
    public void setCelularEmpleado(String celularEmpleado) {
        this.celularEmpleado = celularEmpleado;
    }
    public String getSexoEmpleado() {
        return this.sexoEmpleado;
    }
    
    public void setSexoEmpleado(String sexoEmpleado) {
        this.sexoEmpleado = sexoEmpleado;
    }
    public String getApellidoEmpleado() {
        return this.apellidoEmpleado;
    }
    
    public void setApellidoEmpleado(String apellidoEmpleado) {
        this.apellidoEmpleado = apellidoEmpleado;
    }
    public Boolean getEstadoEmpleado() {
        return this.estadoEmpleado;
    }
    
    public void setEstadoEmpleado(Boolean estadoEmpleado) {
        this.estadoEmpleado = estadoEmpleado;
    }
    public String getFotoEmpleado() {
        return this.fotoEmpleado;
    }
    
    public void setFotoEmpleado(String fotoEmpleado) {
        this.fotoEmpleado = fotoEmpleado;
    }
    public String getLugarNacimientoEmpleado() {
        return this.lugarNacimientoEmpleado;
    }
    
    public void setLugarNacimientoEmpleado(String lugarNacimientoEmpleado) {
        this.lugarNacimientoEmpleado = lugarNacimientoEmpleado;
    }
    public Integer getTipoEmpleado() {
        return this.tipoEmpleado;
    }
    
    public void setTipoEmpleado(Integer tipoEmpleado) {
        this.tipoEmpleado = tipoEmpleado;
    }
    public Boolean getEstadoSocio() {
        return this.estadoSocio;
    }
    
    public void setEstadoSocio(Boolean estadoSocio) {
        this.estadoSocio = estadoSocio;
    }
    public Set getTCapacitacions() {
        return this.TCapacitacions;
    }
    
    public void setTCapacitacions(Set TCapacitacions) {
        this.TCapacitacions = TCapacitacions;
    }
    public Set getTAsesorias() {
        return this.TAsesorias;
    }
    
    public void setTAsesorias(Set TAsesorias) {
        this.TAsesorias = TAsesorias;
    }
    public Set getTEmpleadoCargos() {
        return this.TEmpleadoCargos;
    }
    
    public void setTEmpleadoCargos(Set TEmpleadoCargos) {
        this.TEmpleadoCargos = TEmpleadoCargos;
    }
    public Set getTOcupacions() {
        return this.TOcupacions;
    }
    
    public void setTOcupacions(Set TOcupacions) {
        this.TOcupacions = TOcupacions;
    }
    public Set getTComentarios() {
        return this.TComentarios;
    }
    
    public void setTComentarios(Set TComentarios) {
        this.TComentarios = TComentarios;
    }
    public Set getTSugerencias() {
        return this.TSugerencias;
    }
    
    public void setTSugerencias(Set TSugerencias) {
        this.TSugerencias = TSugerencias;
    }
    public Set getTActivoFijos() {
        return this.TActivoFijos;
    }
    
    public void setTActivoFijos(Set TActivoFijos) {
        this.TActivoFijos = TActivoFijos;
    }
    public Set getTMunicipioEmpleados() {
        return this.TMunicipioEmpleados;
    }
    
    public void setTMunicipioEmpleados(Set TMunicipioEmpleados) {
        this.TMunicipioEmpleados = TMunicipioEmpleados;
    }
    public Set getTUsuarios() {
        return this.TUsuarios;
    }
    
    public void setTUsuarios(Set TUsuarios) {
        this.TUsuarios = TUsuarios;
    }
    public Set getTEmpleadoAreas() {
        return this.TEmpleadoAreas;
    }
    
    public void setTEmpleadoAreas(Set TEmpleadoAreas) {
        this.TEmpleadoAreas = TEmpleadoAreas;
    }




}


