package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1



/**
 * TEntidadProyecto generated by hbm2java
 */
public class TEntidadProyecto  implements java.io.Serializable {


     private int identidadproyecto;
     private TEntidad TEntidad;
     private TProyecto TProyecto;

    public TEntidadProyecto() {
    }

	
    public TEntidadProyecto(int identidadproyecto) {
        this.identidadproyecto = identidadproyecto;
    }
    public TEntidadProyecto(int identidadproyecto, TEntidad TEntidad, TProyecto TProyecto) {
       this.identidadproyecto = identidadproyecto;
       this.TEntidad = TEntidad;
       this.TProyecto = TProyecto;
    }
   
    public int getIdentidadproyecto() {
        return this.identidadproyecto;
    }
    
    public void setIdentidadproyecto(int identidadproyecto) {
        this.identidadproyecto = identidadproyecto;
    }
    public TEntidad getTEntidad() {
        return this.TEntidad;
    }
    
    public void setTEntidad(TEntidad TEntidad) {
        this.TEntidad = TEntidad;
    }
    public TProyecto getTProyecto() {
        return this.TProyecto;
    }
    
    public void setTProyecto(TProyecto TProyecto) {
        this.TProyecto = TProyecto;
    }




}


