package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1

import java.math.BigDecimal;




/**
 * TEstructura generated by hbm2java
 */
public class TEstructura  implements java.io.Serializable {


     private int idEstructura;
     private TCuenta TCuenta;
     private TEjercicio TEjercicio;
     private Integer grupoReporte;
     private Integer tipoReporte;
     private Integer nivelReporte;
     private BigDecimal porMaxEstructura;
     private BigDecimal porMinEstructura;
     private BigDecimal valorRango;
     
    
     
     

    public TEstructura() {
    }

	
    public TEstructura(int idEstructura) {
        this.idEstructura = idEstructura;
    }
    
    
    public TEstructura(BigDecimal valorRango,BigDecimal porMinEstructura,BigDecimal porMaxEstructura, int idEstructura, TCuenta TCuenta, TEjercicio TEjercicio, Integer grupoReporte, Integer tipoReporte, Integer nivelReporte) {
       this.idEstructura = idEstructura;
       this.TCuenta = TCuenta;
       this.TEjercicio = TEjercicio;
       this.grupoReporte = grupoReporte;
       this.tipoReporte = tipoReporte;
       this.nivelReporte = nivelReporte;
       this.porMaxEstructura=porMaxEstructura;
       this.porMinEstructura=porMinEstructura;
       this.valorRango=valorRango;  
    }

   

    
    public BigDecimal getPorMaxEstructura() {
        return porMaxEstructura;
    }

    public void setPorMaxEstructura(BigDecimal porMaxEstructura) {
        this.porMaxEstructura = porMaxEstructura;
    }

    public BigDecimal getPorMinEstructura() {
        return porMinEstructura;
    }

    public void setPorMinEstructura(BigDecimal porMixEstructura) {
        this.porMinEstructura = porMixEstructura;
    }

    public BigDecimal getValorRango() {
        return valorRango;
    }

    public void setValorRango(BigDecimal valorRango) {
        this.valorRango = valorRango;
    }
   
    
    public int getIdEstructura() {
        return this.idEstructura;
    }
    
    public void setIdEstructura(int idEstructura) {
        this.idEstructura = idEstructura;
    }
    public TCuenta getTCuenta() {
        return this.TCuenta;
    }
    
    public void setTCuenta(TCuenta TCuenta) {
        this.TCuenta = TCuenta;
    }

    public TEjercicio getTEjercicio() {
        return TEjercicio;
    }

    public void setTEjercicio(TEjercicio TEjercicio) {
        this.TEjercicio = TEjercicio;
    }
  
    public Integer getGrupoReporte() {
        return this.grupoReporte;
    }
    
    public void setGrupoReporte(Integer grupoReporte) {
        this.grupoReporte = grupoReporte;
    }
    public Integer getTipoReporte() {
        return this.tipoReporte;
    }
    
    public void setTipoReporte(Integer tipoReporte) {
        this.tipoReporte = tipoReporte;
    }
    public Integer getNivelReporte() {
        return this.nivelReporte;
    }
    
    public void setNivelReporte(Integer nivelReporte) {
        this.nivelReporte = nivelReporte;
    }




}


