package com.sigaf.pojo;
// Generated 10-feb-2017 20:31:39 by Hibernate Tools 4.3.1



/**
 * TFiador generated by hbm2java
 */
public class TFiador  implements java.io.Serializable {


     private int idfiador;
     private TProyecto TProyecto;
     private String nombre;
     private String direccion;
     private String correo;
     private String dui;
     private String nit;
     private String telefono1;
     private String telefono2;
     private String prefesion;
     private Float ingresos;
     private Integer estado;

    public TFiador() {
    }

	
    public TFiador(int idfiador) {
        this.idfiador = idfiador;
    }
    public TFiador(int idfiador, TProyecto TProyecto, String nombre, String direccion, String correo, String dui, String nit, String telefono1, String telefono2, String prefesion, Float ingresos, Integer estado) {
       this.idfiador = idfiador;
       this.TProyecto = TProyecto;
       this.nombre = nombre;
       this.direccion = direccion;
       this.correo = correo;
       this.dui = dui;
       this.nit = nit;
       this.telefono1 = telefono1;
       this.telefono2 = telefono2;
       this.prefesion = prefesion;
       this.ingresos = ingresos;
       this.estado = estado;
    }
   
    public int getIdfiador() {
        return this.idfiador;
    }
    
    public void setIdfiador(int idfiador) {
        this.idfiador = idfiador;
    }
    public TProyecto getTProyecto() {
        return this.TProyecto;
    }
    
    public void setTProyecto(TProyecto TProyecto) {
        this.TProyecto = TProyecto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }
    public String getNit() {
        return this.nit;
    }
    
    public void setNit(String nit) {
        this.nit = nit;
    }
    public String getTelefono1() {
        return this.telefono1;
    }
    
    public void setTelefono1(String telefono1) {
        this.telefono1 = telefono1;
    }
    public String getTelefono2() {
        return this.telefono2;
    }
    
    public void setTelefono2(String telefono2) {
        this.telefono2 = telefono2;
    }
    public String getPrefesion() {
        return this.prefesion;
    }
    
    public void setPrefesion(String prefesion) {
        this.prefesion = prefesion;
    }
    public Float getIngresos() {
        return this.ingresos;
    }
    
    public void setIngresos(Float ingresos) {
        this.ingresos = ingresos;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }




}


