package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TGarantia generated by hbm2java
 */
public class TGarantia  implements java.io.Serializable {


     private int idGarantia;
     private TProyecto TProyecto;
     private TTipoGarantia TTipoGarantia;
     private String descripcionPrendariaGarantia;
     private BigDecimal valorPrendariaGarantia;
     private String documentoPrendariaGarantia;
     private String hipotecaHipotecariaGarantia;
     private BigDecimal valorHipotecaGarantia;
     private String ubicacionHipotecaGarantia;
     private String documentoHipotecaGarantia;
     private String nombresSolidariaGarantia;
     private String apellidosSolidariaGarantia;
     private String duiSolidariaGarantia;
     private String nitSolidariaGarantia;
     private String profesionSolidariaGarantia;
     private String lugarSolidariaGarantia;
     private BigDecimal ingresosSolidariaGarantia;
     private String telefonotSolidariaGarantia;
     private String telefonofSolidariaGarantia;
     private String fotocopiaDuiSolidariaGarantia;
     private String fotocopiaNitSolidariaGarantia;

    public TGarantia() {
    }

	
    public TGarantia(int idGarantia) {
        this.idGarantia = idGarantia;
    }
    public TGarantia(int idGarantia, TProyecto TProyecto, TTipoGarantia TTipoGarantia, String descripcionPrendariaGarantia, BigDecimal valorPrendariaGarantia, String documentoPrendariaGarantia, String hipotecaHipotecariaGarantia, BigDecimal valorHipotecaGarantia, String ubicacionHipotecaGarantia, String documentoHipotecaGarantia, String nombresSolidariaGarantia, String apellidosSolidariaGarantia, String duiSolidariaGarantia, String nitSolidariaGarantia, String profesionSolidariaGarantia, String lugarSolidariaGarantia, BigDecimal ingresosSolidariaGarantia, String telefonotSolidariaGarantia, String telefonofSolidariaGarantia, String fotocopiaDuiSolidariaGarantia, String fotocopiaNitSolidariaGarantia) {
       this.idGarantia = idGarantia;
       this.TProyecto = TProyecto;
       this.TTipoGarantia = TTipoGarantia;
       this.descripcionPrendariaGarantia = descripcionPrendariaGarantia;
       this.valorPrendariaGarantia = valorPrendariaGarantia;
       this.documentoPrendariaGarantia = documentoPrendariaGarantia;
       this.hipotecaHipotecariaGarantia = hipotecaHipotecariaGarantia;
       this.valorHipotecaGarantia = valorHipotecaGarantia;
       this.ubicacionHipotecaGarantia = ubicacionHipotecaGarantia;
       this.documentoHipotecaGarantia = documentoHipotecaGarantia;
       this.nombresSolidariaGarantia = nombresSolidariaGarantia;
       this.apellidosSolidariaGarantia = apellidosSolidariaGarantia;
       this.duiSolidariaGarantia = duiSolidariaGarantia;
       this.nitSolidariaGarantia = nitSolidariaGarantia;
       this.profesionSolidariaGarantia = profesionSolidariaGarantia;
       this.lugarSolidariaGarantia = lugarSolidariaGarantia;
       this.ingresosSolidariaGarantia = ingresosSolidariaGarantia;
       this.telefonotSolidariaGarantia = telefonotSolidariaGarantia;
       this.telefonofSolidariaGarantia = telefonofSolidariaGarantia;
       this.fotocopiaDuiSolidariaGarantia = fotocopiaDuiSolidariaGarantia;
       this.fotocopiaNitSolidariaGarantia = fotocopiaNitSolidariaGarantia;
    }
   
    public int getIdGarantia() {
        return this.idGarantia;
    }
    
    public void setIdGarantia(int idGarantia) {
        this.idGarantia = idGarantia;
    }
    public TProyecto getTProyecto() {
        return this.TProyecto;
    }
    
    public void setTProyecto(TProyecto TProyecto) {
        this.TProyecto = TProyecto;
    }
    public TTipoGarantia getTTipoGarantia() {
        return this.TTipoGarantia;
    }
    
    public void setTTipoGarantia(TTipoGarantia TTipoGarantia) {
        this.TTipoGarantia = TTipoGarantia;
    }
    public String getDescripcionPrendariaGarantia() {
        return this.descripcionPrendariaGarantia;
    }
    
    public void setDescripcionPrendariaGarantia(String descripcionPrendariaGarantia) {
        this.descripcionPrendariaGarantia = descripcionPrendariaGarantia;
    }
    public BigDecimal getValorPrendariaGarantia() {
        return this.valorPrendariaGarantia;
    }
    
    public void setValorPrendariaGarantia(BigDecimal valorPrendariaGarantia) {
        this.valorPrendariaGarantia = valorPrendariaGarantia;
    }
    public String getDocumentoPrendariaGarantia() {
        return this.documentoPrendariaGarantia;
    }
    
    public void setDocumentoPrendariaGarantia(String documentoPrendariaGarantia) {
        this.documentoPrendariaGarantia = documentoPrendariaGarantia;
    }
    public String getHipotecaHipotecariaGarantia() {
        return this.hipotecaHipotecariaGarantia;
    }
    
    public void setHipotecaHipotecariaGarantia(String hipotecaHipotecariaGarantia) {
        this.hipotecaHipotecariaGarantia = hipotecaHipotecariaGarantia;
    }
    public BigDecimal getValorHipotecaGarantia() {
        return this.valorHipotecaGarantia;
    }
    
    public void setValorHipotecaGarantia(BigDecimal valorHipotecaGarantia) {
        this.valorHipotecaGarantia = valorHipotecaGarantia;
    }
    public String getUbicacionHipotecaGarantia() {
        return this.ubicacionHipotecaGarantia;
    }
    
    public void setUbicacionHipotecaGarantia(String ubicacionHipotecaGarantia) {
        this.ubicacionHipotecaGarantia = ubicacionHipotecaGarantia;
    }
    public String getDocumentoHipotecaGarantia() {
        return this.documentoHipotecaGarantia;
    }
    
    public void setDocumentoHipotecaGarantia(String documentoHipotecaGarantia) {
        this.documentoHipotecaGarantia = documentoHipotecaGarantia;
    }
    public String getNombresSolidariaGarantia() {
        return this.nombresSolidariaGarantia;
    }
    
    public void setNombresSolidariaGarantia(String nombresSolidariaGarantia) {
        this.nombresSolidariaGarantia = nombresSolidariaGarantia;
    }
    public String getApellidosSolidariaGarantia() {
        return this.apellidosSolidariaGarantia;
    }
    
    public void setApellidosSolidariaGarantia(String apellidosSolidariaGarantia) {
        this.apellidosSolidariaGarantia = apellidosSolidariaGarantia;
    }
    public String getDuiSolidariaGarantia() {
        return this.duiSolidariaGarantia;
    }
    
    public void setDuiSolidariaGarantia(String duiSolidariaGarantia) {
        this.duiSolidariaGarantia = duiSolidariaGarantia;
    }
    public String getNitSolidariaGarantia() {
        return this.nitSolidariaGarantia;
    }
    
    public void setNitSolidariaGarantia(String nitSolidariaGarantia) {
        this.nitSolidariaGarantia = nitSolidariaGarantia;
    }
    public String getProfesionSolidariaGarantia() {
        return this.profesionSolidariaGarantia;
    }
    
    public void setProfesionSolidariaGarantia(String profesionSolidariaGarantia) {
        this.profesionSolidariaGarantia = profesionSolidariaGarantia;
    }
    public String getLugarSolidariaGarantia() {
        return this.lugarSolidariaGarantia;
    }
    
    public void setLugarSolidariaGarantia(String lugarSolidariaGarantia) {
        this.lugarSolidariaGarantia = lugarSolidariaGarantia;
    }
    public BigDecimal getIngresosSolidariaGarantia() {
        return this.ingresosSolidariaGarantia;
    }
    
    public void setIngresosSolidariaGarantia(BigDecimal ingresosSolidariaGarantia) {
        this.ingresosSolidariaGarantia = ingresosSolidariaGarantia;
    }
    public String getTelefonotSolidariaGarantia() {
        return this.telefonotSolidariaGarantia;
    }
    
    public void setTelefonotSolidariaGarantia(String telefonotSolidariaGarantia) {
        this.telefonotSolidariaGarantia = telefonotSolidariaGarantia;
    }
    public String getTelefonofSolidariaGarantia() {
        return this.telefonofSolidariaGarantia;
    }
    
    public void setTelefonofSolidariaGarantia(String telefonofSolidariaGarantia) {
        this.telefonofSolidariaGarantia = telefonofSolidariaGarantia;
    }
    public String getFotocopiaDuiSolidariaGarantia() {
        return this.fotocopiaDuiSolidariaGarantia;
    }
    
    public void setFotocopiaDuiSolidariaGarantia(String fotocopiaDuiSolidariaGarantia) {
        this.fotocopiaDuiSolidariaGarantia = fotocopiaDuiSolidariaGarantia;
    }
    public String getFotocopiaNitSolidariaGarantia() {
        return this.fotocopiaNitSolidariaGarantia;
    }
    
    public void setFotocopiaNitSolidariaGarantia(String fotocopiaNitSolidariaGarantia) {
        this.fotocopiaNitSolidariaGarantia = fotocopiaNitSolidariaGarantia;
    }




}


