package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TIngreso generated by hbm2java
 */
public class TIngreso  implements java.io.Serializable {


     private int idingreso;
     private TProyecto TProyecto;
     private String nombre;
     private String descripcion;
     private BigDecimal valor;
     private Integer estado;
     private BigDecimal salarioActual;
     private Integer tiempoTrabajar;
     private BigDecimal montoPension;
     private BigDecimal otrosIngresos;

    public TIngreso() {
    }

	
    public TIngreso(int idingreso) {
        this.idingreso = idingreso;
    }
    public TIngreso(int idingreso, TProyecto TProyecto, String nombre, String descripcion, BigDecimal valor, Integer estado, BigDecimal salarioActual, Integer tiempoTrabajar, BigDecimal montoPension, BigDecimal otrosIngresos) {
       this.idingreso = idingreso;
       this.TProyecto = TProyecto;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.valor = valor;
       this.estado = estado;
       this.salarioActual = salarioActual;
       this.tiempoTrabajar = tiempoTrabajar;
       this.montoPension = montoPension;
       this.otrosIngresos = otrosIngresos;
    }
   
    public int getIdingreso() {
        return this.idingreso;
    }
    
    public void setIdingreso(int idingreso) {
        this.idingreso = idingreso;
    }
    public TProyecto getTProyecto() {
        return this.TProyecto;
    }
    
    public void setTProyecto(TProyecto TProyecto) {
        this.TProyecto = TProyecto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public BigDecimal getSalarioActual() {
        return this.salarioActual;
    }
    
    public void setSalarioActual(BigDecimal salarioActual) {
        this.salarioActual = salarioActual;
    }
    public Integer getTiempoTrabajar() {
        return this.tiempoTrabajar;
    }
    
    public void setTiempoTrabajar(Integer tiempoTrabajar) {
        this.tiempoTrabajar = tiempoTrabajar;
    }
    public BigDecimal getMontoPension() {
        return this.montoPension;
    }
    
    public void setMontoPension(BigDecimal montoPension) {
        this.montoPension = montoPension;
    }
    public BigDecimal getOtrosIngresos() {
        return this.otrosIngresos;
    }
    
    public void setOtrosIngresos(BigDecimal otrosIngresos) {
        this.otrosIngresos = otrosIngresos;
    }




}


