package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TLisiado generated by hbm2java
 */
public class TLisiado  implements java.io.Serializable {


     private int idLisiado;
     private TCliente TCliente;
     private TMunicipio TMunicipio;
     private String nombreConyugue;
     private String telefonoConyugue;
     private Integer numeroHijos;
     private String nombreHijoMayor;
     private String telefonoHijo;
     private String celularHijo;
     private String tenenciaVivienda;
     private Integer anhosDeResidencia;
     private String propiedades;
     private String presupuesto;
     private Boolean experienciaCrediticia;
     private BigDecimal montoCreditoExperiencia;
     private String institucionCrediticia;
     private String tipoLesion;
     private String otrasEnfermedades;
     private String apellidoConyugue;
     private String apellidoHijo;
     private Integer edadHijo;
      private Integer edadConyugue;

    public Integer getEdadConyugue() {
        return edadConyugue;
    }

    public void setEdadConyugue(Integer edadConyugue) {
        this.edadConyugue = edadConyugue;
    }
     private String cartaLisiado;
     private String lugarTrabajo;
     private String nombreJefe;
     private String cargoTrabajo;
     private String telefonoTrabajo;
     private Set TPropiedadLisiados = new HashSet(0);

    public TLisiado() {
    }

	
    public TLisiado(int idLisiado) {
        this.idLisiado = idLisiado;
    }
    public TLisiado(int idLisiado, TCliente TCliente, TMunicipio TMunicipio, String nombreConyugue, String telefonoConyugue, Integer numeroHijos, String nombreHijoMayor, String telefonoHijo, String celularHijo, String tenenciaVivienda, Integer anhosDeResidencia, String propiedades, String presupuesto, Boolean experienciaCrediticia, BigDecimal montoCreditoExperiencia, String institucionCrediticia, String tipoLesion, String otrasEnfermedades, String apellidoConyugue, String apellidoHijo, Integer edadHijo, Integer edadConyugue, String cartaLisiado, String lugarTrabajo, String nombreJefe, String cargoTrabajo, String telefonoTrabajo, Set TPropiedadLisiados) {
       this.idLisiado = idLisiado;
       this.TCliente = TCliente;
       this.TMunicipio = TMunicipio;
       this.nombreConyugue = nombreConyugue;
       this.telefonoConyugue = telefonoConyugue;
       this.numeroHijos = numeroHijos;
       this.nombreHijoMayor = nombreHijoMayor;
       this.telefonoHijo = telefonoHijo;
       this.celularHijo = celularHijo;
       this.tenenciaVivienda = tenenciaVivienda;
       this.anhosDeResidencia = anhosDeResidencia;
       this.propiedades = propiedades;
       this.presupuesto = presupuesto;
       this.experienciaCrediticia = experienciaCrediticia;
       this.montoCreditoExperiencia = montoCreditoExperiencia;
       this.institucionCrediticia = institucionCrediticia;
       this.tipoLesion = tipoLesion;
       this.otrasEnfermedades = otrasEnfermedades;
       this.apellidoConyugue = apellidoConyugue;
       this.apellidoHijo = apellidoHijo;
       this.edadHijo = edadHijo;
       this.edadConyugue= edadConyugue;
       this.cartaLisiado = cartaLisiado;
       this.lugarTrabajo = lugarTrabajo;
       this.nombreJefe = nombreJefe;
       this.cargoTrabajo = cargoTrabajo;
       this.telefonoTrabajo = telefonoTrabajo;
       this.TPropiedadLisiados = TPropiedadLisiados;
    }
   
    public int getIdLisiado() {
        return this.idLisiado;
    }
    
    public void setIdLisiado(int idLisiado) {
        this.idLisiado = idLisiado;
    }
    public TCliente getTCliente() {
        return this.TCliente;
    }
    
    public void setTCliente(TCliente TCliente) {
        this.TCliente = TCliente;
    }
    public TMunicipio getTMunicipio() {
        return this.TMunicipio;
    }
    
    public void setTMunicipio(TMunicipio TMunicipio) {
        this.TMunicipio = TMunicipio;
    }
    public String getNombreConyugue() {
        return this.nombreConyugue;
    }
    
    public void setNombreConyugue(String nombreConyugue) {
        this.nombreConyugue = nombreConyugue;
    }
    public String getTelefonoConyugue() {
        return this.telefonoConyugue;
    }
    
    public void setTelefonoConyugue(String telefonoConyugue) {
        this.telefonoConyugue = telefonoConyugue;
    }
    public Integer getNumeroHijos() {
        return this.numeroHijos;
    }
    
    public void setNumeroHijos(Integer numeroHijos) {
        this.numeroHijos = numeroHijos;
    }
    public String getNombreHijoMayor() {
        return this.nombreHijoMayor;
    }
    
    public void setNombreHijoMayor(String nombreHijoMayor) {
        this.nombreHijoMayor = nombreHijoMayor;
    }
    public String getTelefonoHijo() {
        return this.telefonoHijo;
    }
    
    public void setTelefonoHijo(String telefonoHijo) {
        this.telefonoHijo = telefonoHijo;
    }
    public String getCelularHijo() {
        return this.celularHijo;
    }
    
    public void setCelularHijo(String celularHijo) {
        this.celularHijo = celularHijo;
    }
    public String getTenenciaVivienda() {
        return this.tenenciaVivienda;
    }
    
    public void setTenenciaVivienda(String tenenciaVivienda) {
        this.tenenciaVivienda = tenenciaVivienda;
    }
    public Integer getAnhosDeResidencia() {
        return this.anhosDeResidencia;
    }
    
    public void setAnhosDeResidencia(Integer anhosDeResidencia) {
        this.anhosDeResidencia = anhosDeResidencia;
    }
    public String getPropiedades() {
        return this.propiedades;
    }
    
    public void setPropiedades(String propiedades) {
        this.propiedades = propiedades;
    }
    public String getPresupuesto() {
        return this.presupuesto;
    }
    
    public void setPresupuesto(String presupuesto) {
        this.presupuesto = presupuesto;
    }
    public Boolean getExperienciaCrediticia() {
        return this.experienciaCrediticia;
    }
    
    public void setExperienciaCrediticia(Boolean experienciaCrediticia) {
        this.experienciaCrediticia = experienciaCrediticia;
    }
    public BigDecimal getMontoCreditoExperiencia() {
        return this.montoCreditoExperiencia;
    }
    
    public void setMontoCreditoExperiencia(BigDecimal montoCreditoExperiencia) {
        this.montoCreditoExperiencia = montoCreditoExperiencia;
    }
    public String getInstitucionCrediticia() {
        return this.institucionCrediticia;
    }
    
    public void setInstitucionCrediticia(String institucionCrediticia) {
        this.institucionCrediticia = institucionCrediticia;
    }
    public String getTipoLesion() {
        return this.tipoLesion;
    }
    
    public void setTipoLesion(String tipoLesion) {
        this.tipoLesion = tipoLesion;
    }
    public String getOtrasEnfermedades() {
        return this.otrasEnfermedades;
    }
    
    public void setOtrasEnfermedades(String otrasEnfermedades) {
        this.otrasEnfermedades = otrasEnfermedades;
    }
    public String getApellidoConyugue() {
        return this.apellidoConyugue;
    }
    
    public void setApellidoConyugue(String apellidoConyugue) {
        this.apellidoConyugue = apellidoConyugue;
    }
    public String getApellidoHijo() {
        return this.apellidoHijo;
    }
    
    public void setApellidoHijo(String apellidoHijo) {
        this.apellidoHijo = apellidoHijo;
    }
    public Integer getEdadHijo() {
        return this.edadHijo;
    }
    
    public void setEdadHijo(Integer edadHijo) {
        this.edadHijo = edadHijo;
    }
    public String getCartaLisiado() {
        return this.cartaLisiado;
    }
    
    public void setCartaLisiado(String cartaLisiado) {
        this.cartaLisiado = cartaLisiado;
    }
    public String getLugarTrabajo() {
        return this.lugarTrabajo;
    }
    
    public void setLugarTrabajo(String lugarTrabajo) {
        this.lugarTrabajo = lugarTrabajo;
    }
    public String getNombreJefe() {
        return this.nombreJefe;
    }
    
    public void setNombreJefe(String nombreJefe) {
        this.nombreJefe = nombreJefe;
    }
    public String getCargoTrabajo() {
        return this.cargoTrabajo;
    }
    
    public void setCargoTrabajo(String cargoTrabajo) {
        this.cargoTrabajo = cargoTrabajo;
    }
    public String getTelefonoTrabajo() {
        return this.telefonoTrabajo;
    }
    
    public void setTelefonoTrabajo(String telefonoTrabajo) {
        this.telefonoTrabajo = telefonoTrabajo;
    }
    public Set getTPropiedadLisiados() {
        return this.TPropiedadLisiados;
    }
    
    public void setTPropiedadLisiados(Set TPropiedadLisiados) {
        this.TPropiedadLisiados = TPropiedadLisiados;
    }




}


