package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TMunicipio generated by hbm2java
 */
public class TMunicipio  implements java.io.Serializable {


     private int idMunicipio;
     private TDepartamento TDepartamento;
     private String nombreMunicipio;
     private Boolean estadoMunicipio;
     private Set TLisiados = new HashSet(0);
     private Set TMunicipioEmpleados = new HashSet(0);

    public TMunicipio() {
    }

	
    public TMunicipio(int idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public TMunicipio(int idMunicipio, TDepartamento TDepartamento, String nombreMunicipio, Boolean estadoMunicipio, Set TLisiados, Set TMunicipioEmpleados) {
       this.idMunicipio = idMunicipio;
       this.TDepartamento = TDepartamento;
       this.nombreMunicipio = nombreMunicipio;
       this.estadoMunicipio = estadoMunicipio;
       this.TLisiados = TLisiados;
       this.TMunicipioEmpleados = TMunicipioEmpleados;
    }
   
    public int getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(int idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public TDepartamento getTDepartamento() {
        return this.TDepartamento;
    }
    
    public void setTDepartamento(TDepartamento TDepartamento) {
        this.TDepartamento = TDepartamento;
    }
    public String getNombreMunicipio() {
        return this.nombreMunicipio;
    }
    
    public void setNombreMunicipio(String nombreMunicipio) {
        this.nombreMunicipio = nombreMunicipio;
    }
    public Boolean getEstadoMunicipio() {
        return this.estadoMunicipio;
    }
    
    public void setEstadoMunicipio(Boolean estadoMunicipio) {
        this.estadoMunicipio = estadoMunicipio;
    }
    public Set getTLisiados() {
        return this.TLisiados;
    }
    
    public void setTLisiados(Set TLisiados) {
        this.TLisiados = TLisiados;
    }
    public Set getTMunicipioEmpleados() {
        return this.TMunicipioEmpleados;
    }
    
    public void setTMunicipioEmpleados(Set TMunicipioEmpleados) {
        this.TMunicipioEmpleados = TMunicipioEmpleados;
    }




}


