package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1



/**
 * TMunicipioEmpleado generated by hbm2java
 */
public class TMunicipioEmpleado  implements java.io.Serializable {


     private int idEmpleadoMunicipio;
     private TEmpleado TEmpleado;
     private TMunicipio TMunicipio;
     private Integer tipodireccionMunicipioEmpleado;
     private String direccionEmpleado;

    public TMunicipioEmpleado() {
    }

	
    public TMunicipioEmpleado(int idEmpleadoMunicipio) {
        this.idEmpleadoMunicipio = idEmpleadoMunicipio;
    }
    public TMunicipioEmpleado(int idEmpleadoMunicipio, TEmpleado TEmpleado, TMunicipio TMunicipio, Integer tipodireccionMunicipioEmpleado, String direccionEmpleado) {
       this.idEmpleadoMunicipio = idEmpleadoMunicipio;
       this.TEmpleado = TEmpleado;
       this.TMunicipio = TMunicipio;
       this.tipodireccionMunicipioEmpleado = tipodireccionMunicipioEmpleado;
       this.direccionEmpleado = direccionEmpleado;
    }
   
    public int getIdEmpleadoMunicipio() {
        return this.idEmpleadoMunicipio;
    }
    
    public void setIdEmpleadoMunicipio(int idEmpleadoMunicipio) {
        this.idEmpleadoMunicipio = idEmpleadoMunicipio;
    }
    public TEmpleado getTEmpleado() {
        return this.TEmpleado;
    }
    
    public void setTEmpleado(TEmpleado TEmpleado) {
        this.TEmpleado = TEmpleado;
    }
    public TMunicipio getTMunicipio() {
        return this.TMunicipio;
    }
    
    public void setTMunicipio(TMunicipio TMunicipio) {
        this.TMunicipio = TMunicipio;
    }
    public Integer getTipodireccionMunicipioEmpleado() {
        return this.tipodireccionMunicipioEmpleado;
    }
    
    public void setTipodireccionMunicipioEmpleado(Integer tipodireccionMunicipioEmpleado) {
        this.tipodireccionMunicipioEmpleado = tipodireccionMunicipioEmpleado;
    }
    public String getDireccionEmpleado() {
        return this.direccionEmpleado;
    }
    
    public void setDireccionEmpleado(String direccionEmpleado) {
        this.direccionEmpleado = direccionEmpleado;
    }




}


