package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1



/**
 * TOcupacion generated by hbm2java
 */
public class TOcupacion  implements java.io.Serializable {


     private int idOcupacion;
     private TEmpleado TEmpleado;
     private String nombreOcupacion;
     private Boolean estadoOcupacion;

    public TOcupacion() {
    }

	
    public TOcupacion(int idOcupacion) {
        this.idOcupacion = idOcupacion;
    }
    public TOcupacion(int idOcupacion, TEmpleado TEmpleado, String nombreOcupacion, Boolean estadoOcupacion) {
       this.idOcupacion = idOcupacion;
       this.TEmpleado = TEmpleado;
       this.nombreOcupacion = nombreOcupacion;
       this.estadoOcupacion = estadoOcupacion;
    }
   
    public int getIdOcupacion() {
        return this.idOcupacion;
    }
    
    public void setIdOcupacion(int idOcupacion) {
        this.idOcupacion = idOcupacion;
    }
    public TEmpleado getTEmpleado() {
        return this.TEmpleado;
    }
    
    public void setTEmpleado(TEmpleado TEmpleado) {
        this.TEmpleado = TEmpleado;
    }
    public String getNombreOcupacion() {
        return this.nombreOcupacion;
    }
    
    public void setNombreOcupacion(String nombreOcupacion) {
        this.nombreOcupacion = nombreOcupacion;
    }
    public Boolean getEstadoOcupacion() {
        return this.estadoOcupacion;
    }
    
    public void setEstadoOcupacion(Boolean estadoOcupacion) {
        this.estadoOcupacion = estadoOcupacion;
    }




}


