package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * TPagoAgronegocio generated by hbm2java
 */
public class TPagoAgronegocio  implements java.io.Serializable {


     private int idPagoAgronegocio;
     private TAgronegocio TAgronegocio;
     private BigDecimal monto;
     private Date fecha;
     private BigDecimal interes;
     private BigDecimal otrosinteres;
     private String hora;
     private String forma;
     private String cheque;
     private Integer dias;
     private BigDecimal comision;
     private Integer referencia;

    public Integer getReferencia() {
        return referencia;
    }

    public void setReferencia(Integer referencia) {
        this.referencia = referencia;
    }

    public TPagoAgronegocio() {
    }

	
    public TPagoAgronegocio(int idPagoAgronegocio) {
        this.idPagoAgronegocio = idPagoAgronegocio;
    }
    public TPagoAgronegocio(int idPagoAgronegocio, Integer referencia, TAgronegocio TAgronegocio, BigDecimal monto, Date fecha, BigDecimal interes, BigDecimal otrosinteres, String hora, String forma, String cheque, Integer dias, BigDecimal comision) {
       this.idPagoAgronegocio = idPagoAgronegocio;
       this.TAgronegocio = TAgronegocio;
       this.monto = monto;
       this.fecha = fecha;
       this.interes = interes;
       this.otrosinteres = otrosinteres;
       this.hora = hora;
       this.forma = forma;
       this.cheque = cheque;
       this.dias = dias;
       this.comision = comision;
       this.referencia= referencia;
    }
   
    public int getIdPagoAgronegocio() {
        return this.idPagoAgronegocio;
    }
    
    public void setIdPagoAgronegocio(int idPagoAgronegocio) {
        this.idPagoAgronegocio = idPagoAgronegocio;
    }
    public TAgronegocio getTAgronegocio() {
        return this.TAgronegocio;
    }
    
    public void setTAgronegocio(TAgronegocio TAgronegocio) {
        this.TAgronegocio = TAgronegocio;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public BigDecimal getInteres() {
        return this.interes;
    }
    
    public void setInteres(BigDecimal interes) {
        this.interes = interes;
    }
    public BigDecimal getOtrosinteres() {
        return this.otrosinteres;
    }
    
    public void setOtrosinteres(BigDecimal otrosinteres) {
        this.otrosinteres = otrosinteres;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public String getForma() {
        return this.forma;
    }
    
    public void setForma(String forma) {
        this.forma = forma;
    }
    public String getCheque() {
        return this.cheque;
    }
    
    public void setCheque(String cheque) {
        this.cheque = cheque;
    }
    public Integer getDias() {
        return this.dias;
    }
    
    public void setDias(Integer dias) {
        this.dias = dias;
    }
    public BigDecimal getComision() {
        return this.comision;
    }
    
    public void setComision(BigDecimal comision) {
        this.comision = comision;
    }




}


