package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TPartida generated by hbm2java
 */
public class TPartida  implements java.io.Serializable {


     private int idPartida;
     private TPeriodo TPeriodo;
     private Date fechaPartida;
     private String conceptoPartida;
     private Integer numeroPartida;
     private Boolean estadoPartida;
     private Set TDetallePartidas = new HashSet(0);
     private Set TDepreciacions = new HashSet(0);
     private Set TBajaActivoFijos = new HashSet(0);
     private Set TValorActivos = new HashSet(0);

    public TPartida() {
    }

	
    public TPartida(int idPartida) {
        this.idPartida = idPartida;
    }
    public TPartida(int idPartida, TPeriodo TPeriodo, Date fechaPartida, String conceptoPartida, Integer numeroPartida, Boolean estadoPartida, Set TDetallePartidas, Set TDepreciacions, Set TBajaActivoFijos, Set TValorActivos) {
       this.idPartida = idPartida;
       this.TPeriodo = TPeriodo;
       this.fechaPartida = fechaPartida;
       this.conceptoPartida = conceptoPartida;
       this.numeroPartida = numeroPartida;
       this.estadoPartida = estadoPartida;
       this.TDetallePartidas = TDetallePartidas;
       this.TDepreciacions = TDepreciacions;
       this.TBajaActivoFijos = TBajaActivoFijos;
       this.TValorActivos = TValorActivos;
    }
   
    public int getIdPartida() {
        return this.idPartida;
    }
    
    public void setIdPartida(int idPartida) {
        this.idPartida = idPartida;
    }
    public TPeriodo getTPeriodo() {
        return this.TPeriodo;
    }
    
    public void setTPeriodo(TPeriodo TPeriodo) {
        this.TPeriodo = TPeriodo;
    }
    public Date getFechaPartida() {
        return this.fechaPartida;
    }
    
    public void setFechaPartida(Date fechaPartida) {
        this.fechaPartida = fechaPartida;
    }
    public String getConceptoPartida() {
        return this.conceptoPartida;
    }
    
    public void setConceptoPartida(String conceptoPartida) {
        this.conceptoPartida = conceptoPartida;
    }
    public Integer getNumeroPartida() {
        return this.numeroPartida;
    }
    
    public void setNumeroPartida(Integer numeroPartida) {
        this.numeroPartida = numeroPartida;
    }
    public Boolean getEstadoPartida() {
        return this.estadoPartida;
    }
    
    public void setEstadoPartida(Boolean estadoPartida) {
        this.estadoPartida = estadoPartida;
    }
    public Set getTDetallePartidas() {
        return this.TDetallePartidas;
    }
    
    public void setTDetallePartidas(Set TDetallePartidas) {
        this.TDetallePartidas = TDetallePartidas;
    }
    public Set getTDepreciacions() {
        return this.TDepreciacions;
    }
    
    public void setTDepreciacions(Set TDepreciacions) {
        this.TDepreciacions = TDepreciacions;
    }
    public Set getTBajaActivoFijos() {
        return this.TBajaActivoFijos;
    }
    
    public void setTBajaActivoFijos(Set TBajaActivoFijos) {
        this.TBajaActivoFijos = TBajaActivoFijos;
    }
    public Set getTValorActivos() {
        return this.TValorActivos;
    }
    
    public void setTValorActivos(Set TValorActivos) {
        this.TValorActivos = TValorActivos;
    }




}


