package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TPasivo generated by hbm2java
 */
public class TPasivo  implements java.io.Serializable {


     private int idpasivo;
     private TProyecto TProyecto;
     private String nombre;
     private String descripcion;
     private BigDecimal valorpasivo;
     private Integer estado;

    public TPasivo() {
    }

	
    public TPasivo(int idpasivo) {
        this.idpasivo = idpasivo;
    }
    public TPasivo(int idpasivo, TProyecto TProyecto, String nombre, String descripcion, BigDecimal valorpasivo, Integer estado) {
       this.idpasivo = idpasivo;
       this.TProyecto = TProyecto;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.valorpasivo = valorpasivo;
       this.estado = estado;
    }
   
    public int getIdpasivo() {
        return this.idpasivo;
    }
    
    public void setIdpasivo(int idpasivo) {
        this.idpasivo = idpasivo;
    }
    public TProyecto getTProyecto() {
        return this.TProyecto;
    }
    
    public void setTProyecto(TProyecto TProyecto) {
        this.TProyecto = TProyecto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getValorpasivo() {
        return this.valorpasivo;
    }
    
    public void setValorpasivo(BigDecimal valorpasivo) {
        this.valorpasivo = valorpasivo;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }




}


