package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TPolitica generated by hbm2java
 */
public class TPolitica  implements java.io.Serializable {


     private int idPolitica;
     private TTipoCredito TTipoCredito;
     private BigDecimal tasaInteres;
     private Integer edadMaxima;
     private Integer edadMinima;
     private BigDecimal montoMinimo;
     private BigDecimal montoMaximo;
     private BigDecimal tasaInteresMora;
     private BigDecimal comision;
     private BigDecimal seguroDeuda;
     private BigDecimal capacidadPagoMinimo;
     private BigDecimal capacidadEndeudamientoMinimo;
     private Boolean estado;
     private Set TProyectos = new HashSet(0);

    public TPolitica() {
    }

	
    public TPolitica(int idPolitica) {
        this.idPolitica = idPolitica;
    }
    public TPolitica(int idPolitica, TTipoCredito TTipoCredito, BigDecimal tasaInteres, Integer edadMaxima, Integer edadMinima, BigDecimal montoMinimo, BigDecimal montoMaximo, BigDecimal tasaInteresMora, BigDecimal comision, BigDecimal seguroDeuda, BigDecimal capacidadPagoMinimo, BigDecimal capacidadEndeudamientoMinimo, Boolean estado, Set TProyectos) {
       this.idPolitica = idPolitica;
       this.TTipoCredito = TTipoCredito;
       this.tasaInteres = tasaInteres;
       this.edadMaxima = edadMaxima;
       this.edadMinima = edadMinima;
       this.montoMinimo = montoMinimo;
       this.montoMaximo = montoMaximo;
       this.tasaInteresMora = tasaInteresMora;
       this.comision = comision;
       this.seguroDeuda = seguroDeuda;
       this.capacidadPagoMinimo = capacidadPagoMinimo;
       this.capacidadEndeudamientoMinimo = capacidadEndeudamientoMinimo;
       this.estado = estado;
       this.TProyectos = TProyectos;
    }
   
    public int getIdPolitica() {
        return this.idPolitica;
    }
    
    public void setIdPolitica(int idPolitica) {
        this.idPolitica = idPolitica;
    }
    public TTipoCredito getTTipoCredito() {
        return this.TTipoCredito;
    }
    
    public void setTTipoCredito(TTipoCredito TTipoCredito) {
        this.TTipoCredito = TTipoCredito;
    }
    public BigDecimal getTasaInteres() {
        return this.tasaInteres;
    }
    
    public void setTasaInteres(BigDecimal tasaInteres) {
        this.tasaInteres = tasaInteres;
    }
    public Integer getEdadMaxima() {
        return this.edadMaxima;
    }
    
    public void setEdadMaxima(Integer edadMaxima) {
        this.edadMaxima = edadMaxima;
    }
    public Integer getEdadMinima() {
        return this.edadMinima;
    }
    
    public void setEdadMinima(Integer edadMinima) {
        this.edadMinima = edadMinima;
    }
    public BigDecimal getMontoMinimo() {
        return this.montoMinimo;
    }
    
    public void setMontoMinimo(BigDecimal montoMinimo) {
        this.montoMinimo = montoMinimo;
    }
    public BigDecimal getMontoMaximo() {
        return this.montoMaximo;
    }
    
    public void setMontoMaximo(BigDecimal montoMaximo) {
        this.montoMaximo = montoMaximo;
    }
    public BigDecimal getTasaInteresMora() {
        return this.tasaInteresMora;
    }
    
    public void setTasaInteresMora(BigDecimal tasaInteresMora) {
        this.tasaInteresMora = tasaInteresMora;
    }
    public BigDecimal getComision() {
        return this.comision;
    }
    
    public void setComision(BigDecimal comision) {
        this.comision = comision;
    }
    public BigDecimal getSeguroDeuda() {
        return this.seguroDeuda;
    }
    
    public void setSeguroDeuda(BigDecimal seguroDeuda) {
        this.seguroDeuda = seguroDeuda;
    }
    public BigDecimal getCapacidadPagoMinimo() {
        return this.capacidadPagoMinimo;
    }
    
    public void setCapacidadPagoMinimo(BigDecimal capacidadPagoMinimo) {
        this.capacidadPagoMinimo = capacidadPagoMinimo;
    }
    public BigDecimal getCapacidadEndeudamientoMinimo() {
        return this.capacidadEndeudamientoMinimo;
    }
    
    public void setCapacidadEndeudamientoMinimo(BigDecimal capacidadEndeudamientoMinimo) {
        this.capacidadEndeudamientoMinimo = capacidadEndeudamientoMinimo;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getTProyectos() {
        return this.TProyectos;
    }
    
    public void setTProyectos(Set TProyectos) {
        this.TProyectos = TProyectos;
    }




}


