package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TProyecto generated by hbm2java
 */
public class TProyecto  implements java.io.Serializable {


     private int idproyecto;
     private TPolitica TPolitica;
     private TTipoCredito TTipoCredito;
     private String nombre;
     private BigDecimal monto;
     private Integer plazo;
     private Date fecha;
     private Integer estado;
     private String codigo;
     private String descripcion;
     private String lugar;
     private String calificacion;
     private String codigoProyecto;
     private String estadoProyecto;
     private Date fechaAprovacion;
     private Integer formaPagoProyecto;
     private String destinoProyecto;
     private Date fechaVencimientoProyecto;
     private Date fechaFinalizacionProyecto;

    public Date getFechaFinalizacionProyecto() {
        return fechaFinalizacionProyecto;
    }

    public void setFechaFinalizacionProyecto(Date fechaFinalizacionProyecto) {
        this.fechaFinalizacionProyecto = fechaFinalizacionProyecto;
    }
     private Set TAgropecuarios = new HashSet(0);
     private Set TIngresos = new HashSet(0);
     private Set TSeguimientos = new HashSet(0);
     private Set TActivos = new HashSet(0);
     private Set TReferencias = new HashSet(0);
     private Set TAsesorias = new HashSet(0);
     private Set TClienteProyectos = new HashSet(0);
     private Set TIndividuals = new HashSet(0);
     private Set TCapacitacions = new HashSet(0);
     private Set TEgresos = new HashSet(0);
     private Set TCooperativas = new HashSet(0);
     private Set TPagos = new HashSet(0);
     private Set TComercios = new HashSet(0);
     private Set TDesembolsos = new HashSet(0);
     private Set TEmpleadoCreditos = new HashSet(0);
     private Set TSugerencias = new HashSet(0);
     private Set TComentarios = new HashSet(0);
     private Set TGarantias = new HashSet(0);
     private Set TPasivos = new HashSet(0);
     private Set TEntidadProyectos = new HashSet(0);

    public TProyecto() {
    }

	
    public TProyecto(int idproyecto) {
        this.idproyecto = idproyecto;
    }
    public TProyecto(int idproyecto, TPolitica TPolitica, TTipoCredito TTipoCredito, String nombre, BigDecimal monto, Integer plazo, Date fecha,Date fechaFinalizacionProyecto, Integer estado, String codigo, String descripcion, String lugar, String calificacion, String codigoProyecto, String estadoProyecto, Date fechaAprovacion, Integer formaPagoProyecto, String destinoProyecto, Date fechaVencimientoProyecto, Set TAgropecuarios, Set TIngresos, Set TSeguimientos, Set TActivos, Set TReferencias, Set TAsesorias, Set TClienteProyectos, Set TIndividuals, Set TCapacitacions, Set TEgresos, Set TCooperativas, Set TPagos, Set TComercios, Set TDesembolsos, Set TEmpleadoCreditos, Set TSugerencias, Set TComentarios, Set TGarantias, Set TPasivos, Set TEntidadProyectos) {
       this.idproyecto = idproyecto;
       this.TPolitica = TPolitica;
       this.TTipoCredito = TTipoCredito;
       this.nombre = nombre;
       this.monto = monto;
       this.plazo = plazo;
       this.fecha = fecha;
       this.estado = estado;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.lugar = lugar;
       this.calificacion = calificacion;
       this.codigoProyecto = codigoProyecto;
       this.estadoProyecto = estadoProyecto;
       this.fechaAprovacion = fechaAprovacion;
       this.formaPagoProyecto = formaPagoProyecto;
       this.destinoProyecto = destinoProyecto;
       this.fechaVencimientoProyecto = fechaVencimientoProyecto;
       this.fechaFinalizacionProyecto= fechaFinalizacionProyecto;
       this.TAgropecuarios = TAgropecuarios;
       this.TIngresos = TIngresos;
       this.TSeguimientos = TSeguimientos;
       this.TActivos = TActivos;
       this.TReferencias = TReferencias;
       this.TAsesorias = TAsesorias;
       this.TClienteProyectos = TClienteProyectos;
       this.TIndividuals = TIndividuals;
       this.TCapacitacions = TCapacitacions;
       this.TEgresos = TEgresos;
       this.TCooperativas = TCooperativas;
       this.TPagos = TPagos;
       this.TComercios = TComercios;
       this.TDesembolsos = TDesembolsos;
       this.TEmpleadoCreditos = TEmpleadoCreditos;
       this.TSugerencias = TSugerencias;
       this.TComentarios = TComentarios;
       this.TGarantias = TGarantias;
       this.TPasivos = TPasivos;
       this.TEntidadProyectos = TEntidadProyectos;
    }
   
    public int getIdproyecto() {
        return this.idproyecto;
    }
    
    public void setIdproyecto(int idproyecto) {
        this.idproyecto = idproyecto;
    }
    public TPolitica getTPolitica() {
        return this.TPolitica;
    }
    
    public void setTPolitica(TPolitica TPolitica) {
        this.TPolitica = TPolitica;
    }
    public TTipoCredito getTTipoCredito() {
        return this.TTipoCredito;
    }
    
    public void setTTipoCredito(TTipoCredito TTipoCredito) {
        this.TTipoCredito = TTipoCredito;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }
    public Integer getPlazo() {
        return this.plazo;
    }
    
    public void setPlazo(Integer plazo) {
        this.plazo = plazo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public String getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(String calificacion) {
        this.calificacion = calificacion;
    }
    public String getCodigoProyecto() {
        return this.codigoProyecto;
    }
    
    public void setCodigoProyecto(String codigoProyecto) {
        this.codigoProyecto = codigoProyecto;
    }
    public String getEstadoProyecto() {
        return this.estadoProyecto;
    }
    
    public void setEstadoProyecto(String estadoProyecto) {
        this.estadoProyecto = estadoProyecto;
    }
    public Date getFechaAprovacion() {
        return this.fechaAprovacion;
    }
    
    public void setFechaAprovacion(Date fechaAprovacion) {
        this.fechaAprovacion = fechaAprovacion;
    }
    public Integer getFormaPagoProyecto() {
        return this.formaPagoProyecto;
    }
    
    public void setFormaPagoProyecto(Integer formaPagoProyecto) {
        this.formaPagoProyecto = formaPagoProyecto;
    }
    public String getDestinoProyecto() {
        return this.destinoProyecto;
    }
    
    public void setDestinoProyecto(String destinoProyecto) {
        this.destinoProyecto = destinoProyecto;
    }
    public Date getFechaVencimientoProyecto() {
        return this.fechaVencimientoProyecto;
    }
    
    public void setFechaVencimientoProyecto(Date fechaVencimientoProyecto) {
        this.fechaVencimientoProyecto = fechaVencimientoProyecto;
    }
    public Set getTAgropecuarios() {
        return this.TAgropecuarios;
    }
    
    public void setTAgropecuarios(Set TAgropecuarios) {
        this.TAgropecuarios = TAgropecuarios;
    }
    public Set getTIngresos() {
        return this.TIngresos;
    }
    
    public void setTIngresos(Set TIngresos) {
        this.TIngresos = TIngresos;
    }
    public Set getTSeguimientos() {
        return this.TSeguimientos;
    }
    
    public void setTSeguimientos(Set TSeguimientos) {
        this.TSeguimientos = TSeguimientos;
    }
    public Set getTActivos() {
        return this.TActivos;
    }
    
    public void setTActivos(Set TActivos) {
        this.TActivos = TActivos;
    }
    public Set getTReferencias() {
        return this.TReferencias;
    }
    
    public void setTReferencias(Set TReferencias) {
        this.TReferencias = TReferencias;
    }
    public Set getTAsesorias() {
        return this.TAsesorias;
    }
    
    public void setTAsesorias(Set TAsesorias) {
        this.TAsesorias = TAsesorias;
    }
    public Set getTClienteProyectos() {
        return this.TClienteProyectos;
    }
    
    public void setTClienteProyectos(Set TClienteProyectos) {
        this.TClienteProyectos = TClienteProyectos;
    }
    public Set getTIndividuals() {
        return this.TIndividuals;
    }
    
    public void setTIndividuals(Set TIndividuals) {
        this.TIndividuals = TIndividuals;
    }
    public Set getTCapacitacions() {
        return this.TCapacitacions;
    }
    
    public void setTCapacitacions(Set TCapacitacions) {
        this.TCapacitacions = TCapacitacions;
    }
    public Set getTEgresos() {
        return this.TEgresos;
    }
    
    public void setTEgresos(Set TEgresos) {
        this.TEgresos = TEgresos;
    }
    public Set getTCooperativas() {
        return this.TCooperativas;
    }
    
    public void setTCooperativas(Set TCooperativas) {
        this.TCooperativas = TCooperativas;
    }
    public Set getTPagos() {
        return this.TPagos;
    }
    
    public void setTPagos(Set TPagos) {
        this.TPagos = TPagos;
    }
    public Set getTComercios() {
        return this.TComercios;
    }
    
    public void setTComercios(Set TComercios) {
        this.TComercios = TComercios;
    }
    public Set getTDesembolsos() {
        return this.TDesembolsos;
    }
    
    public void setTDesembolsos(Set TDesembolsos) {
        this.TDesembolsos = TDesembolsos;
    }
    public Set getTEmpleadoCreditos() {
        return this.TEmpleadoCreditos;
    }
    
    public void setTEmpleadoCreditos(Set TEmpleadoCreditos) {
        this.TEmpleadoCreditos = TEmpleadoCreditos;
    }
    public Set getTSugerencias() {
        return this.TSugerencias;
    }
    
    public void setTSugerencias(Set TSugerencias) {
        this.TSugerencias = TSugerencias;
    }
    public Set getTComentarios() {
        return this.TComentarios;
    }
    
    public void setTComentarios(Set TComentarios) {
        this.TComentarios = TComentarios;
    }
    public Set getTGarantias() {
        return this.TGarantias;
    }
    
    public void setTGarantias(Set TGarantias) {
        this.TGarantias = TGarantias;
    }
    public Set getTPasivos() {
        return this.TPasivos;
    }
    
    public void setTPasivos(Set TPasivos) {
        this.TPasivos = TPasivos;
    }
    public Set getTEntidadProyectos() {
        return this.TEntidadProyectos;
    }
    
    public void setTEntidadProyectos(Set TEntidadProyectos) {
        this.TEntidadProyectos = TEntidadProyectos;
    }




}


