package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1



/**
 * TProductoCooperativa generated by hbm2java
 */
public class TProductoCooperativa  implements java.io.Serializable {


     private int idProductoCooperativa;
     private TEntidad TEntidad;
     private TProducto TProducto;

    public TProductoCooperativa() {
    }

	
    public TProductoCooperativa(int idProductoCooperativa) {
        this.idProductoCooperativa = idProductoCooperativa;
    }
    public TProductoCooperativa(int idProductoCooperativa, TEntidad TEntidad, TProducto TProducto) {
       this.idProductoCooperativa = idProductoCooperativa;
       this.TEntidad = TEntidad;
       this.TProducto = TProducto;
    }
   
    public int getIdProductoCooperativa() {
        return this.idProductoCooperativa;
    }
    
    public void setIdProductoCooperativa(int idProductoCooperativa) {
        this.idProductoCooperativa = idProductoCooperativa;
    }
    public TEntidad getTEntidad() {
        return this.TEntidad;
    }
    
    public void setTEntidad(TEntidad TEntidad) {
        this.TEntidad = TEntidad;
    }
    public TProducto getTProducto() {
        return this.TProducto;
    }
    
    public void setTProducto(TProducto TProducto) {
        this.TProducto = TProducto;
    }




}


