package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1



/**
 * TProductoProductor generated by hbm2java
 */
public class TProductoProductor  implements java.io.Serializable {


     private int idproductoproductor;
     private TProducto TProducto;
     private TProductorIndividual TProductorIndividual;

    public TProductoProductor() {
    }

	
    public TProductoProductor(int idproductoproductor) {
        this.idproductoproductor = idproductoproductor;
    }
    public TProductoProductor(int idproductoproductor, TProducto TProducto, TProductorIndividual TProductorIndividual) {
       this.idproductoproductor = idproductoproductor;
       this.TProducto = TProducto;
       this.TProductorIndividual = TProductorIndividual;
    }
   
    public int getIdproductoproductor() {
        return this.idproductoproductor;
    }
    
    public void setIdproductoproductor(int idproductoproductor) {
        this.idproductoproductor = idproductoproductor;
    }
    public TProducto getTProducto() {
        return this.TProducto;
    }
    
    public void setTProducto(TProducto TProducto) {
        this.TProducto = TProducto;
    }
    public TProductorIndividual getTProductorIndividual() {
        return this.TProductorIndividual;
    }
    
    public void setTProductorIndividual(TProductorIndividual TProductorIndividual) {
        this.TProductorIndividual = TProductorIndividual;
    }




}


