package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TProveedor generated by hbm2java
 */
public class TProveedor  implements java.io.Serializable {


     private int idProveedor;
     private TEntidad TEntidad;
     private String nombreProveedor;
     private String giroProveedor;
     private String correoProveedor;
     private String direccionProveedor;
     private String nitProveedor;
     private String telefono1Proveedor;
     private String telefono2Proveedor;
     private String nrcProveedor;
     private Boolean estadoProveedor;
     private Set TActivoFijos = new HashSet(0);

    public TProveedor() {
    }

	
    public TProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public TProveedor(int idProveedor, TEntidad TEntidad, String nombreProveedor, String giroProveedor, String correoProveedor, String direccionProveedor, String nitProveedor, String telefono1Proveedor, String telefono2Proveedor, String nrcProveedor, Boolean estadoProveedor, Set TActivoFijos) {
       this.idProveedor = idProveedor;
       this.TEntidad = TEntidad;
       this.nombreProveedor = nombreProveedor;
       this.giroProveedor = giroProveedor;
       this.correoProveedor = correoProveedor;
       this.direccionProveedor = direccionProveedor;
       this.nitProveedor = nitProveedor;
       this.telefono1Proveedor = telefono1Proveedor;
       this.telefono2Proveedor = telefono2Proveedor;
       this.nrcProveedor = nrcProveedor;
       this.estadoProveedor = estadoProveedor;
       this.TActivoFijos = TActivoFijos;
    }
   
    public int getIdProveedor() {
        return this.idProveedor;
    }
    
    public void setIdProveedor(int idProveedor) {
        this.idProveedor = idProveedor;
    }
    public TEntidad getTEntidad() {
        return this.TEntidad;
    }
    
    public void setTEntidad(TEntidad TEntidad) {
        this.TEntidad = TEntidad;
    }
    public String getNombreProveedor() {
        return this.nombreProveedor;
    }
    
    public void setNombreProveedor(String nombreProveedor) {
        this.nombreProveedor = nombreProveedor;
    }
    public String getGiroProveedor() {
        return this.giroProveedor;
    }
    
    public void setGiroProveedor(String giroProveedor) {
        this.giroProveedor = giroProveedor;
    }
    public String getCorreoProveedor() {
        return this.correoProveedor;
    }
    
    public void setCorreoProveedor(String correoProveedor) {
        this.correoProveedor = correoProveedor;
    }
    public String getDireccionProveedor() {
        return this.direccionProveedor;
    }
    
    public void setDireccionProveedor(String direccionProveedor) {
        this.direccionProveedor = direccionProveedor;
    }
    public String getNitProveedor() {
        return this.nitProveedor;
    }
    
    public void setNitProveedor(String nitProveedor) {
        this.nitProveedor = nitProveedor;
    }
    public String getTelefono1Proveedor() {
        return this.telefono1Proveedor;
    }
    
    public void setTelefono1Proveedor(String telefono1Proveedor) {
        this.telefono1Proveedor = telefono1Proveedor;
    }
    public String getTelefono2Proveedor() {
        return this.telefono2Proveedor;
    }
    
    public void setTelefono2Proveedor(String telefono2Proveedor) {
        this.telefono2Proveedor = telefono2Proveedor;
    }
    public String getNrcProveedor() {
        return this.nrcProveedor;
    }
    
    public void setNrcProveedor(String nrcProveedor) {
        this.nrcProveedor = nrcProveedor;
    }
    public Boolean getEstadoProveedor() {
        return this.estadoProveedor;
    }
    
    public void setEstadoProveedor(Boolean estadoProveedor) {
        this.estadoProveedor = estadoProveedor;
    }
    public Set getTActivoFijos() {
        return this.TActivoFijos;
    }
    
    public void setTActivoFijos(Set TActivoFijos) {
        this.TActivoFijos = TActivoFijos;
    }




}


