package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TProducto generated by hbm2java
 */
public class TProducto  implements java.io.Serializable {


     private int idproducto;
     private TTipoCultivo TTipoCultivo;
     private String nombre;
     private String sistema;
     private Boolean asistencia;
     private String organizacion;
     private Boolean estado;
     private Set TProductoProductors = new HashSet(0);
     private Set TProductoCooperativas = new HashSet(0);
     private Set TProductoAgronegocios = new HashSet(0);

    public TProducto() {
    }

	
    public TProducto(int idproducto) {
        this.idproducto = idproducto;
    }
    public TProducto(int idproducto, TTipoCultivo TTipoCultivo, String nombre, String sistema, Boolean asistencia, String organizacion, Boolean estado, Set TProductoProductors, Set TProductoCooperativas, Set TProductoAgronegocios) {
       this.idproducto = idproducto;
       this.TTipoCultivo = TTipoCultivo;
       this.nombre = nombre;
       this.sistema = sistema;
       this.asistencia = asistencia;
       this.organizacion = organizacion;
       this.estado = estado;
       this.TProductoProductors = TProductoProductors;
       this.TProductoCooperativas = TProductoCooperativas;
       this.TProductoAgronegocios = TProductoAgronegocios;
    }
   
    public int getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(int idproducto) {
        this.idproducto = idproducto;
    }
    public TTipoCultivo getTTipoCultivo() {
        return this.TTipoCultivo;
    }
    
    public void setTTipoCultivo(TTipoCultivo TTipoCultivo) {
        this.TTipoCultivo = TTipoCultivo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getSistema() {
        return this.sistema;
    }
    
    public void setSistema(String sistema) {
        this.sistema = sistema;
    }
    public Boolean getAsistencia() {
        return this.asistencia;
    }
    
    public void setAsistencia(Boolean asistencia) {
        this.asistencia = asistencia;
    }
    public String getOrganizacion() {
        return this.organizacion;
    }
    
    public void setOrganizacion(String organizacion) {
        this.organizacion = organizacion;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Set getTProductoProductors() {
        return this.TProductoProductors;
    }
    
    public void setTProductoProductors(Set TProductoProductors) {
        this.TProductoProductors = TProductoProductors;
    }
    public Set getTProductoCooperativas() {
        return this.TProductoCooperativas;
    }
    
    public void setTProductoCooperativas(Set TProductoCooperativas) {
        this.TProductoCooperativas = TProductoCooperativas;
    }
    public Set getTProductoAgronegocios() {
        return this.TProductoAgronegocios;
    }
    
    public void setTProductoAgronegocios(Set TProductoAgronegocios) {
        this.TProductoAgronegocios = TProductoAgronegocios;
    }




}


