package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TProductorGrupal generated by hbm2java
 */
public class TProductorGrupal  implements java.io.Serializable {


     private int idProductorGrupal;
     private String codigoProdcutorGrupal;
     private String nombreProductorGrupal;
     private Integer hombresProductorGrupal;
     private Integer mujeresProductorGrupal;
     private String contactoProductorGrupal;
     private String duiProductorGrupal;
     private String nitProductorGrupal;
     private String correoProductorGrupal;
     private String telefonoProductorGrupal;
     private String movilProductorGrupal;
     private String ubicacionProductorGrupal;
     private Boolean estadoProductorGrupal;
     private Integer calificacionProductorGrupal;
     private Set TProductorIndividuals = new HashSet(0);

    public TProductorGrupal() {
    }

	
    public TProductorGrupal(int idProductorGrupal) {
        this.idProductorGrupal = idProductorGrupal;
    }
    public TProductorGrupal(int idProductorGrupal, String codigoProdcutorGrupal, String nombreProductorGrupal, Integer hombresProductorGrupal, Integer mujeresProductorGrupal, String contactoProductorGrupal, String duiProductorGrupal, String nitProductorGrupal, String correoProductorGrupal, String telefonoProductorGrupal, String movilProductorGrupal, String ubicacionProductorGrupal, Boolean estadoProductorGrupal, Integer calificacionProductorGrupal, Set TProductorIndividuals) {
       this.idProductorGrupal = idProductorGrupal;
       this.codigoProdcutorGrupal = codigoProdcutorGrupal;
       this.nombreProductorGrupal = nombreProductorGrupal;
       this.hombresProductorGrupal = hombresProductorGrupal;
       this.mujeresProductorGrupal = mujeresProductorGrupal;
       this.contactoProductorGrupal = contactoProductorGrupal;
       this.duiProductorGrupal = duiProductorGrupal;
       this.nitProductorGrupal = nitProductorGrupal;
       this.correoProductorGrupal = correoProductorGrupal;
       this.telefonoProductorGrupal = telefonoProductorGrupal;
       this.movilProductorGrupal = movilProductorGrupal;
       this.ubicacionProductorGrupal = ubicacionProductorGrupal;
       this.estadoProductorGrupal = estadoProductorGrupal;
       this.calificacionProductorGrupal = calificacionProductorGrupal;
       this.TProductorIndividuals = TProductorIndividuals;
    }
   
    public int getIdProductorGrupal() {
        return this.idProductorGrupal;
    }
    
    public void setIdProductorGrupal(int idProductorGrupal) {
        this.idProductorGrupal = idProductorGrupal;
    }
    public String getCodigoProdcutorGrupal() {
        return this.codigoProdcutorGrupal;
    }
    
    public void setCodigoProdcutorGrupal(String codigoProdcutorGrupal) {
        this.codigoProdcutorGrupal = codigoProdcutorGrupal;
    }
    public String getNombreProductorGrupal() {
        return this.nombreProductorGrupal;
    }
    
    public void setNombreProductorGrupal(String nombreProductorGrupal) {
        this.nombreProductorGrupal = nombreProductorGrupal;
    }
    public Integer getHombresProductorGrupal() {
        return this.hombresProductorGrupal;
    }
    
    public void setHombresProductorGrupal(Integer hombresProductorGrupal) {
        this.hombresProductorGrupal = hombresProductorGrupal;
    }
    public Integer getMujeresProductorGrupal() {
        return this.mujeresProductorGrupal;
    }
    
    public void setMujeresProductorGrupal(Integer mujeresProductorGrupal) {
        this.mujeresProductorGrupal = mujeresProductorGrupal;
    }
    public String getContactoProductorGrupal() {
        return this.contactoProductorGrupal;
    }
    
    public void setContactoProductorGrupal(String contactoProductorGrupal) {
        this.contactoProductorGrupal = contactoProductorGrupal;
    }
    public String getDuiProductorGrupal() {
        return this.duiProductorGrupal;
    }
    
    public void setDuiProductorGrupal(String duiProductorGrupal) {
        this.duiProductorGrupal = duiProductorGrupal;
    }
    public String getNitProductorGrupal() {
        return this.nitProductorGrupal;
    }
    
    public void setNitProductorGrupal(String nitProductorGrupal) {
        this.nitProductorGrupal = nitProductorGrupal;
    }
    public String getCorreoProductorGrupal() {
        return this.correoProductorGrupal;
    }
    
    public void setCorreoProductorGrupal(String correoProductorGrupal) {
        this.correoProductorGrupal = correoProductorGrupal;
    }
    public String getTelefonoProductorGrupal() {
        return this.telefonoProductorGrupal;
    }
    
    public void setTelefonoProductorGrupal(String telefonoProductorGrupal) {
        this.telefonoProductorGrupal = telefonoProductorGrupal;
    }
    public String getMovilProductorGrupal() {
        return this.movilProductorGrupal;
    }
    
    public void setMovilProductorGrupal(String movilProductorGrupal) {
        this.movilProductorGrupal = movilProductorGrupal;
    }
    public String getUbicacionProductorGrupal() {
        return this.ubicacionProductorGrupal;
    }
    
    public void setUbicacionProductorGrupal(String ubicacionProductorGrupal) {
        this.ubicacionProductorGrupal = ubicacionProductorGrupal;
    }
    public Boolean getEstadoProductorGrupal() {
        return this.estadoProductorGrupal;
    }
    
    public void setEstadoProductorGrupal(Boolean estadoProductorGrupal) {
        this.estadoProductorGrupal = estadoProductorGrupal;
    }
    public Integer getCalificacionProductorGrupal() {
        return this.calificacionProductorGrupal;
    }
    
    public void setCalificacionProductorGrupal(Integer calificacionProductorGrupal) {
        this.calificacionProductorGrupal = calificacionProductorGrupal;
    }
    public Set getTProductorIndividuals() {
        return this.TProductorIndividuals;
    }
    
    public void setTProductorIndividuals(Set TProductorIndividuals) {
        this.TProductorIndividuals = TProductorIndividuals;
    }




}


