package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TProductorIndividual generated by hbm2java
 */
public class TProductorIndividual  implements java.io.Serializable {


     private int idProductorIndividual;
     private TProductorGrupal TProductorGrupal;
     private String codigoProductorIndividual;
     private String nombresProdcutorIndividual;
     private String apellidosProductorIndividual;
     private Date fechanacimientoProductorIndividual;
     private String duiProductorIndividual;
     private String nitProductorIndividual;
     private String sexoProductorIndividual;
     private Integer varonesProductorIndividual;
     private Integer ninasProductorIndividual;
     private String experienciaProductorIndividual;
     private String institucionProductorIndividual;
     private String estudioProductorIndividual;
     private String actividadesProductorIndividual;
     private String correoProductorIndividual;
     private String telefonoProductorIndividual;
     private String movilProductorIndividual;
     private String direccionProductorIndividual;
     private Boolean estadoProductorIndividual;
     private Integer calificacionProductorIndividual;
     private String estadoFamiliarProductorIndividual;
     private Boolean representanteGrupal;
     private Set TProductoProductors = new HashSet(0);

    public TProductorIndividual() {
    }

	
    public TProductorIndividual(int idProductorIndividual) {
        this.idProductorIndividual = idProductorIndividual;
    }
    public TProductorIndividual(int idProductorIndividual, TProductorGrupal TProductorGrupal, String codigoProductorIndividual, String nombresProdcutorIndividual, String apellidosProductorIndividual, Date fechanacimientoProductorIndividual, String duiProductorIndividual, String nitProductorIndividual, String sexoProductorIndividual, Integer varonesProductorIndividual, Integer ninasProductorIndividual, String experienciaProductorIndividual, String institucionProductorIndividual, String estudioProductorIndividual, String actividadesProductorIndividual, String correoProductorIndividual, String telefonoProductorIndividual, String movilProductorIndividual, String direccionProductorIndividual, Boolean estadoProductorIndividual, Integer calificacionProductorIndividual, String estadoFamiliarProductorIndividual, Boolean representanteGrupal, Set TProductoProductors) {
       this.idProductorIndividual = idProductorIndividual;
       this.TProductorGrupal = TProductorGrupal;
       this.codigoProductorIndividual = codigoProductorIndividual;
       this.nombresProdcutorIndividual = nombresProdcutorIndividual;
       this.apellidosProductorIndividual = apellidosProductorIndividual;
       this.fechanacimientoProductorIndividual = fechanacimientoProductorIndividual;
       this.duiProductorIndividual = duiProductorIndividual;
       this.nitProductorIndividual = nitProductorIndividual;
       this.sexoProductorIndividual = sexoProductorIndividual;
       this.varonesProductorIndividual = varonesProductorIndividual;
       this.ninasProductorIndividual = ninasProductorIndividual;
       this.experienciaProductorIndividual = experienciaProductorIndividual;
       this.institucionProductorIndividual = institucionProductorIndividual;
       this.estudioProductorIndividual = estudioProductorIndividual;
       this.actividadesProductorIndividual = actividadesProductorIndividual;
       this.correoProductorIndividual = correoProductorIndividual;
       this.telefonoProductorIndividual = telefonoProductorIndividual;
       this.movilProductorIndividual = movilProductorIndividual;
       this.direccionProductorIndividual = direccionProductorIndividual;
       this.estadoProductorIndividual = estadoProductorIndividual;
       this.calificacionProductorIndividual = calificacionProductorIndividual;
       this.estadoFamiliarProductorIndividual = estadoFamiliarProductorIndividual;
       this.representanteGrupal = representanteGrupal;
       this.TProductoProductors = TProductoProductors;
    }
   
    public int getIdProductorIndividual() {
        return this.idProductorIndividual;
    }
    
    public void setIdProductorIndividual(int idProductorIndividual) {
        this.idProductorIndividual = idProductorIndividual;
    }
    public TProductorGrupal getTProductorGrupal() {
        return this.TProductorGrupal;
    }
    
    public void setTProductorGrupal(TProductorGrupal TProductorGrupal) {
        this.TProductorGrupal = TProductorGrupal;
    }
    public String getCodigoProductorIndividual() {
        return this.codigoProductorIndividual;
    }
    
    public void setCodigoProductorIndividual(String codigoProductorIndividual) {
        this.codigoProductorIndividual = codigoProductorIndividual;
    }
    public String getNombresProdcutorIndividual() {
        return this.nombresProdcutorIndividual;
    }
    
    public void setNombresProdcutorIndividual(String nombresProdcutorIndividual) {
        this.nombresProdcutorIndividual = nombresProdcutorIndividual;
    }
    public String getApellidosProductorIndividual() {
        return this.apellidosProductorIndividual;
    }
    
    public void setApellidosProductorIndividual(String apellidosProductorIndividual) {
        this.apellidosProductorIndividual = apellidosProductorIndividual;
    }
    public Date getFechanacimientoProductorIndividual() {
        return this.fechanacimientoProductorIndividual;
    }
    
    public void setFechanacimientoProductorIndividual(Date fechanacimientoProductorIndividual) {
        this.fechanacimientoProductorIndividual = fechanacimientoProductorIndividual;
    }
    public String getDuiProductorIndividual() {
        return this.duiProductorIndividual;
    }
    
    public void setDuiProductorIndividual(String duiProductorIndividual) {
        this.duiProductorIndividual = duiProductorIndividual;
    }
    public String getNitProductorIndividual() {
        return this.nitProductorIndividual;
    }
    
    public void setNitProductorIndividual(String nitProductorIndividual) {
        this.nitProductorIndividual = nitProductorIndividual;
    }
    public String getSexoProductorIndividual() {
        return this.sexoProductorIndividual;
    }
    
    public void setSexoProductorIndividual(String sexoProductorIndividual) {
        this.sexoProductorIndividual = sexoProductorIndividual;
    }
    public Integer getVaronesProductorIndividual() {
        return this.varonesProductorIndividual;
    }
    
    public void setVaronesProductorIndividual(Integer varonesProductorIndividual) {
        this.varonesProductorIndividual = varonesProductorIndividual;
    }
    public Integer getNinasProductorIndividual() {
        return this.ninasProductorIndividual;
    }
    
    public void setNinasProductorIndividual(Integer ninasProductorIndividual) {
        this.ninasProductorIndividual = ninasProductorIndividual;
    }
    public String getExperienciaProductorIndividual() {
        return this.experienciaProductorIndividual;
    }
    
    public void setExperienciaProductorIndividual(String experienciaProductorIndividual) {
        this.experienciaProductorIndividual = experienciaProductorIndividual;
    }
    public String getInstitucionProductorIndividual() {
        return this.institucionProductorIndividual;
    }
    
    public void setInstitucionProductorIndividual(String institucionProductorIndividual) {
        this.institucionProductorIndividual = institucionProductorIndividual;
    }
    public String getEstudioProductorIndividual() {
        return this.estudioProductorIndividual;
    }
    
    public void setEstudioProductorIndividual(String estudioProductorIndividual) {
        this.estudioProductorIndividual = estudioProductorIndividual;
    }
    public String getActividadesProductorIndividual() {
        return this.actividadesProductorIndividual;
    }
    
    public void setActividadesProductorIndividual(String actividadesProductorIndividual) {
        this.actividadesProductorIndividual = actividadesProductorIndividual;
    }
    public String getCorreoProductorIndividual() {
        return this.correoProductorIndividual;
    }
    
    public void setCorreoProductorIndividual(String correoProductorIndividual) {
        this.correoProductorIndividual = correoProductorIndividual;
    }
    public String getTelefonoProductorIndividual() {
        return this.telefonoProductorIndividual;
    }
    
    public void setTelefonoProductorIndividual(String telefonoProductorIndividual) {
        this.telefonoProductorIndividual = telefonoProductorIndividual;
    }
    public String getMovilProductorIndividual() {
        return this.movilProductorIndividual;
    }
    
    public void setMovilProductorIndividual(String movilProductorIndividual) {
        this.movilProductorIndividual = movilProductorIndividual;
    }
    public String getDireccionProductorIndividual() {
        return this.direccionProductorIndividual;
    }
    
    public void setDireccionProductorIndividual(String direccionProductorIndividual) {
        this.direccionProductorIndividual = direccionProductorIndividual;
    }
    public Boolean getEstadoProductorIndividual() {
        return this.estadoProductorIndividual;
    }
    
    public void setEstadoProductorIndividual(Boolean estadoProductorIndividual) {
        this.estadoProductorIndividual = estadoProductorIndividual;
    }
    public Integer getCalificacionProductorIndividual() {
        return this.calificacionProductorIndividual;
    }
    
    public void setCalificacionProductorIndividual(Integer calificacionProductorIndividual) {
        this.calificacionProductorIndividual = calificacionProductorIndividual;
    }
    public String getEstadoFamiliarProductorIndividual() {
        return this.estadoFamiliarProductorIndividual;
    }
    
    public void setEstadoFamiliarProductorIndividual(String estadoFamiliarProductorIndividual) {
        this.estadoFamiliarProductorIndividual = estadoFamiliarProductorIndividual;
    }
    public Boolean getRepresentanteGrupal() {
        return this.representanteGrupal;
    }
    
    public void setRepresentanteGrupal(Boolean representanteGrupal) {
        this.representanteGrupal = representanteGrupal;
    }
    public Set getTProductoProductors() {
        return this.TProductoProductors;
    }
    
    public void setTProductoProductors(Set TProductoProductors) {
        this.TProductoProductors = TProductoProductors;
    }




}


