package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TProductoAgronegocio generated by hbm2java
 */
public class TProductoAgronegocio  implements java.io.Serializable {


     private int idProductoAgronegocio;
     private TAgronegocio TAgronegocio;
     private TProducto TProducto;
     private String nombre;
     private String unidad;
     private Integer cantidad;
     private BigDecimal precio;

    public TProductoAgronegocio() {
    }

	
    public TProductoAgronegocio(int idProductoAgronegocio) {
        this.idProductoAgronegocio = idProductoAgronegocio;
    }
    public TProductoAgronegocio(int idProductoAgronegocio, TAgronegocio TAgronegocio, TProducto TProducto, String nombre, String unidad, Integer cantidad, BigDecimal precio) {
       this.idProductoAgronegocio = idProductoAgronegocio;
       this.TAgronegocio = TAgronegocio;
       this.TProducto = TProducto;
       this.nombre = nombre;
       this.unidad = unidad;
       this.cantidad = cantidad;
       this.precio = precio;
    }
   
    public int getIdProductoAgronegocio() {
        return this.idProductoAgronegocio;
    }
    
    public void setIdProductoAgronegocio(int idProductoAgronegocio) {
        this.idProductoAgronegocio = idProductoAgronegocio;
    }
    public TAgronegocio getTAgronegocio() {
        return this.TAgronegocio;
    }
    
    public void setTAgronegocio(TAgronegocio TAgronegocio) {
        this.TAgronegocio = TAgronegocio;
    }
    public TProducto getTProducto() {
        return this.TProducto;
    }
    
    public void setTProducto(TProducto TProducto) {
        this.TProducto = TProducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }




}


