package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1



/**
 * TPropiedadLisiado generated by hbm2java
 */
public class TPropiedadLisiado  implements java.io.Serializable {


     private int idPropiedadLisiado;
     private TLisiado TLisiado;
     private String nombrePropiedad;

    public TPropiedadLisiado() {
    }

	
    public TPropiedadLisiado(int idPropiedadLisiado) {
        this.idPropiedadLisiado = idPropiedadLisiado;
    }
    public TPropiedadLisiado(int idPropiedadLisiado, TLisiado TLisiado, String nombrePropiedad) {
       this.idPropiedadLisiado = idPropiedadLisiado;
       this.TLisiado = TLisiado;
       this.nombrePropiedad = nombrePropiedad;
    }
   
    public int getIdPropiedadLisiado() {
        return this.idPropiedadLisiado;
    }
    
    public void setIdPropiedadLisiado(int idPropiedadLisiado) {
        this.idPropiedadLisiado = idPropiedadLisiado;
    }
    public TLisiado getTLisiado() {
        return this.TLisiado;
    }
    
    public void setTLisiado(TLisiado TLisiado) {
        this.TLisiado = TLisiado;
    }
    public String getNombrePropiedad() {
        return this.nombrePropiedad;
    }
    
    public void setNombrePropiedad(String nombrePropiedad) {
        this.nombrePropiedad = nombrePropiedad;
    }




}


