package com.sigaf.pojo;
// Generated 05-07-2017 10:04:17 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TSeguimiento generated by hbm2java
 */
public class TSeguimiento  implements java.io.Serializable {


     private int idseguimiento;
     private TProyecto TProyecto;
     private String descripcion;
     private Integer estado;
     private Date fechaseguimiento;
     private Set TParametros = new HashSet(0);

    public TSeguimiento() {
    }

	
    public TSeguimiento(int idseguimiento) {
        this.idseguimiento = idseguimiento;
    }
    public TSeguimiento(int idseguimiento, TProyecto TProyecto, String descripcion, Integer estado, Date fechaseguimiento, Set TParametros) {
       this.idseguimiento = idseguimiento;
       this.TProyecto = TProyecto;
       this.descripcion = descripcion;
       this.estado = estado;
       this.fechaseguimiento = fechaseguimiento;
       this.TParametros = TParametros;
    }
   
    public int getIdseguimiento() {
        return this.idseguimiento;
    }
    
    public void setIdseguimiento(int idseguimiento) {
        this.idseguimiento = idseguimiento;
    }
    public TProyecto getTProyecto() {
        return this.TProyecto;
    }
    
    public void setTProyecto(TProyecto TProyecto) {
        this.TProyecto = TProyecto;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Date getFechaseguimiento() {
        return this.fechaseguimiento;
    }
    
    public void setFechaseguimiento(Date fechaseguimiento) {
        this.fechaseguimiento = fechaseguimiento;
    }
    public Set getTParametros() {
        return this.TParametros;
    }
    
    public void setTParametros(Set TParametros) {
        this.TParametros = TParametros;
    }




}


