package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TTipoCultivo generated by hbm2java
 */
public class TTipoCultivo  implements java.io.Serializable {


     private int idTipoCultivo;
     private TAreaCultivo TAreaCultivo;
     private String nombreTipoCultivo;
     private Boolean estadoTipoCultivo;
     private Set TProductos = new HashSet(0);

    public TTipoCultivo() {
    }

	
    public TTipoCultivo(int idTipoCultivo) {
        this.idTipoCultivo = idTipoCultivo;
    }
    public TTipoCultivo(int idTipoCultivo, TAreaCultivo TAreaCultivo, String nombreTipoCultivo, Boolean estadoTipoCultivo, Set TProductos) {
       this.idTipoCultivo = idTipoCultivo;
       this.TAreaCultivo = TAreaCultivo;
       this.nombreTipoCultivo = nombreTipoCultivo;
       this.estadoTipoCultivo = estadoTipoCultivo;
       this.TProductos = TProductos;
    }
   
    public int getIdTipoCultivo() {
        return this.idTipoCultivo;
    }
    
    public void setIdTipoCultivo(int idTipoCultivo) {
        this.idTipoCultivo = idTipoCultivo;
    }
    public TAreaCultivo getTAreaCultivo() {
        return this.TAreaCultivo;
    }
    
    public void setTAreaCultivo(TAreaCultivo TAreaCultivo) {
        this.TAreaCultivo = TAreaCultivo;
    }
    public String getNombreTipoCultivo() {
        return this.nombreTipoCultivo;
    }
    
    public void setNombreTipoCultivo(String nombreTipoCultivo) {
        this.nombreTipoCultivo = nombreTipoCultivo;
    }
    public Boolean getEstadoTipoCultivo() {
        return this.estadoTipoCultivo;
    }
    
    public void setEstadoTipoCultivo(Boolean estadoTipoCultivo) {
        this.estadoTipoCultivo = estadoTipoCultivo;
    }
    public Set getTProductos() {
        return this.TProductos;
    }
    
    public void setTProductos(Set TProductos) {
        this.TProductos = TProductos;
    }




}


