package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TTipoActivo generated by hbm2java
 */
public class TTipoActivo  implements java.io.Serializable {


     private int idTipo;
     private TCuenta TCuentaByIdCuentaVentaTipo;
     private TCuenta TCuentaByIdCuentaDepreciacionTipo;
     private TCuenta TCuentaByIdCuentaGastoTipo;
     private TCuenta TCuentaByIdCuentaActivoTipo;
     private TEntidad TEntidad;
     private String nombreTipo;
     private String descripcionTipo;
     private String codigoTipo;
     private Integer vidaUtilTipo;
      private String calculoTipoActivo;
     private Boolean estadoTipo;
     private Set TActivoFijos = new HashSet(0);

    public TTipoActivo() {
    }

	
    public TTipoActivo(int idTipo) {
        this.idTipo = idTipo;
    }
    public TTipoActivo(int idTipo, TCuenta TCuentaByIdCuentaVentaTipo, TCuenta TCuentaByIdCuentaDepreciacionTipo, TCuenta TCuentaByIdCuentaGastoTipo, TCuenta TCuentaByIdCuentaActivoTipo, TEntidad TEntidad, String nombreTipo, String descripcionTipo, String codigoTipo, Integer vidaUtilTipo,String calculoTipoActivo, Boolean estadoTipo, Set TActivoFijos) {
       this.idTipo = idTipo;
       this.TCuentaByIdCuentaVentaTipo = TCuentaByIdCuentaVentaTipo;
       this.TCuentaByIdCuentaDepreciacionTipo = TCuentaByIdCuentaDepreciacionTipo;
       this.TCuentaByIdCuentaGastoTipo = TCuentaByIdCuentaGastoTipo;
       this.TCuentaByIdCuentaActivoTipo = TCuentaByIdCuentaActivoTipo;
       this.TEntidad = TEntidad;
       this.nombreTipo = nombreTipo;
       this.descripcionTipo = descripcionTipo;
       this.codigoTipo = codigoTipo;
       this.vidaUtilTipo = vidaUtilTipo;
       this.calculoTipoActivo=calculoTipoActivo;
       this.estadoTipo = estadoTipo;
       this.TActivoFijos = TActivoFijos;
    }

    public String getCalculoTipoActivo() {
        return calculoTipoActivo;
    }

    public void setCalculoTipoActivo(String calculoTipoActivo) {
        this.calculoTipoActivo = calculoTipoActivo;
    }
   
    public int getIdTipo() {
        return this.idTipo;
    }
    
    public void setIdTipo(int idTipo) {
        this.idTipo = idTipo;
    }
    public TCuenta getTCuentaByIdCuentaVentaTipo() {
        return this.TCuentaByIdCuentaVentaTipo;
    }
    
    public void setTCuentaByIdCuentaVentaTipo(TCuenta TCuentaByIdCuentaVentaTipo) {
        this.TCuentaByIdCuentaVentaTipo = TCuentaByIdCuentaVentaTipo;
    }
    public TCuenta getTCuentaByIdCuentaDepreciacionTipo() {
        return this.TCuentaByIdCuentaDepreciacionTipo;
    }
    
    public void setTCuentaByIdCuentaDepreciacionTipo(TCuenta TCuentaByIdCuentaDepreciacionTipo) {
        this.TCuentaByIdCuentaDepreciacionTipo = TCuentaByIdCuentaDepreciacionTipo;
    }
    public TCuenta getTCuentaByIdCuentaGastoTipo() {
        return this.TCuentaByIdCuentaGastoTipo;
    }
    
    public void setTCuentaByIdCuentaGastoTipo(TCuenta TCuentaByIdCuentaGastoTipo) {
        this.TCuentaByIdCuentaGastoTipo = TCuentaByIdCuentaGastoTipo;
    }
    public TCuenta getTCuentaByIdCuentaActivoTipo() {
        return this.TCuentaByIdCuentaActivoTipo;
    }
    
    public void setTCuentaByIdCuentaActivoTipo(TCuenta TCuentaByIdCuentaActivoTipo) {
        this.TCuentaByIdCuentaActivoTipo = TCuentaByIdCuentaActivoTipo;
    }
    public TEntidad getTEntidad() {
        return this.TEntidad;
    }
    
    public void setTEntidad(TEntidad TEntidad) {
        this.TEntidad = TEntidad;
    }
    public String getNombreTipo() {
        return this.nombreTipo;
    }
    
    public void setNombreTipo(String nombreTipo) {
        this.nombreTipo = nombreTipo;
    }
    public String getDescripcionTipo() {
        return this.descripcionTipo;
    }
    
    public void setDescripcionTipo(String descripcionTipo) {
        this.descripcionTipo = descripcionTipo;
    }
    public String getCodigoTipo() {
        return this.codigoTipo;
    }
    
    public void setCodigoTipo(String codigoTipo) {
        this.codigoTipo = codigoTipo;
    }
    public Integer getVidaUtilTipo() {
        return this.vidaUtilTipo;
    }
    
    public void setVidaUtilTipo(Integer vidaUtilTipo) {
        this.vidaUtilTipo = vidaUtilTipo;
    }
    public Boolean getEstadoTipo() {
        return this.estadoTipo;
    }
    
    public void setEstadoTipo(Boolean estadoTipo) {
        this.estadoTipo = estadoTipo;
    }
    public Set getTActivoFijos() {
        return this.TActivoFijos;
    }
    
    public void setTActivoFijos(Set TActivoFijos) {
        this.TActivoFijos = TActivoFijos;
    }




}


