package com.sigaf.pojo;
// Generated 04-03-2017 03:09:46 PM by Hibernate Tools 4.3.1



/**
 * TTrabajo generated by hbm2java
 */
public class TTrabajo  implements java.io.Serializable {


     private int idTrabajo;
     private TCliente TCliente;
     private String nombreEmpresa;
     private String telefonoEmpresa;
     private String direccionEmpresa;
     private String cargoEmpresa;
     private Integer tiempoEmpresa;
     private String constancia;

    public TTrabajo() {
    }

	
    public TTrabajo(int idTrabajo) {
        this.idTrabajo = idTrabajo;
    }
    public TTrabajo(int idTrabajo, TCliente TCliente, String nombreEmpresa, String telefonoEmpresa, String direccionEmpresa, String cargoEmpresa, Integer tiempoEmpresa, String constancia) {
       this.idTrabajo = idTrabajo;
       this.TCliente = TCliente;
       this.nombreEmpresa = nombreEmpresa;
       this.telefonoEmpresa = telefonoEmpresa;
       this.direccionEmpresa = direccionEmpresa;
       this.cargoEmpresa = cargoEmpresa;
       this.tiempoEmpresa = tiempoEmpresa;
       this.constancia = constancia;
    }
   
    public int getIdTrabajo() {
        return this.idTrabajo;
    }
    
    public void setIdTrabajo(int idTrabajo) {
        this.idTrabajo = idTrabajo;
    }
    public TCliente getTCliente() {
        return this.TCliente;
    }
    
    public void setTCliente(TCliente TCliente) {
        this.TCliente = TCliente;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getTelefonoEmpresa() {
        return this.telefonoEmpresa;
    }
    
    public void setTelefonoEmpresa(String telefonoEmpresa) {
        this.telefonoEmpresa = telefonoEmpresa;
    }
    public String getDireccionEmpresa() {
        return this.direccionEmpresa;
    }
    
    public void setDireccionEmpresa(String direccionEmpresa) {
        this.direccionEmpresa = direccionEmpresa;
    }
    public String getCargoEmpresa() {
        return this.cargoEmpresa;
    }
    
    public void setCargoEmpresa(String cargoEmpresa) {
        this.cargoEmpresa = cargoEmpresa;
    }
    public Integer getTiempoEmpresa() {
        return this.tiempoEmpresa;
    }
    
    public void setTiempoEmpresa(Integer tiempoEmpresa) {
        this.tiempoEmpresa = tiempoEmpresa;
    }
    public String getConstancia() {
        return this.constancia;
    }
    
    public void setConstancia(String constancia) {
        this.constancia = constancia;
    }




}


