package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TUsuario generated by hbm2java
 */
public class TUsuario  implements java.io.Serializable {


     private int idUsuario;
     private TEmpleado TEmpleado;
     private String nombreUsuario;
     private String claveUsuario;
     private Boolean estadoUsuario;
     private Integer tipoUsuario;
     private Set TBitacoras = new HashSet(0);

    public TUsuario() {
    }

	
    public TUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public TUsuario(int idUsuario, TEmpleado TEmpleado, String nombreUsuario, String claveUsuario, Boolean estadoUsuario, Integer tipoUsuario, Set TBitacoras) {
       this.idUsuario = idUsuario;
       this.TEmpleado = TEmpleado;
       this.nombreUsuario = nombreUsuario;
       this.claveUsuario = claveUsuario;
       this.estadoUsuario = estadoUsuario;
       this.tipoUsuario = tipoUsuario;
       this.TBitacoras = TBitacoras;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public TEmpleado getTEmpleado() {
        return this.TEmpleado;
    }
    
    public void setTEmpleado(TEmpleado TEmpleado) {
        this.TEmpleado = TEmpleado;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getClaveUsuario() {
        return this.claveUsuario;
    }
    
    public void setClaveUsuario(String claveUsuario) {
        this.claveUsuario = claveUsuario;
    }
    public Boolean getEstadoUsuario() {
        return this.estadoUsuario;
    }
    
    public void setEstadoUsuario(Boolean estadoUsuario) {
        this.estadoUsuario = estadoUsuario;
    }
    public Integer getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(Integer tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Set getTBitacoras() {
        return this.TBitacoras;
    }
    
    public void setTBitacoras(Set TBitacoras) {
        this.TBitacoras = TBitacoras;
    }




}


