package com.sigaf.pojo;
// Generated 05-mar-2017 20:43:44 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * TValorActivo generated by hbm2java
 */
public class TValorActivo  implements java.io.Serializable {


     private int idValorActivo;
     private TActivoFijo TActivoFijo;
     private TPartida TPartida;
     private BigDecimal valorActivo;

    public TValorActivo() {
    }

	
    public TValorActivo(int idValorActivo) {
        this.idValorActivo = idValorActivo;
    }
    public TValorActivo(int idValorActivo, TActivoFijo TActivoFijo, TPartida TPartida, BigDecimal valorActivo) {
       this.idValorActivo = idValorActivo;
       this.TActivoFijo = TActivoFijo;
       this.TPartida = TPartida;
       this.valorActivo = valorActivo;
    }
   
    public int getIdValorActivo() {
        return this.idValorActivo;
    }
    
    public void setIdValorActivo(int idValorActivo) {
        this.idValorActivo = idValorActivo;
    }
    public TActivoFijo getTActivoFijo() {
        return this.TActivoFijo;
    }
    
    public void setTActivoFijo(TActivoFijo TActivoFijo) {
        this.TActivoFijo = TActivoFijo;
    }
    public TPartida getTPartida() {
        return this.TPartida;
    }
    
    public void setTPartida(TPartida TPartida) {
        this.TPartida = TPartida;
    }
    public BigDecimal getValorActivo() {
        return this.valorActivo;
    }
    
    public void setValorActivo(BigDecimal valorActivo) {
        this.valorActivo = valorActivo;
    }




}


